### DISCUSSION TITLE
Warn users in the UI about needing to add "dokploy-network" to all services when configuring a domain

### DISCUSSION THREAD

**Discussion by nktnet1** [Dokploy/dokploy#1067] [General]
For example, supposed the user defines this docker-compose for umami (copied from GitHub or a third party source rather than using an existing template, for demo purposes):

```yaml
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DATABASE_TYPE: postgresql
      APP_SECRET: ${APP_SECRET}

  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - 9123:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  db-data:
```

Then hits "deploy". Everything works as expected.

They then go and add a domain and re-deploy. Suddenly, their application can no longer connect to the database. Isn't immediately obvious why.

The reason is because Dokploy injects the following to the umami service (only visible when you click "preview compose":
```yaml
    networks:
      - dokploy-network
```

but does not automatically do the same for the database.

---

## Suggestions

When a domain is first configured:
1. Check and add dokploy-network automatically to all services if missing (probably not a good idea)
2. Check and add another local/private network to all services in the compose
3. In the domains tab, warn users about needing to add the "dokploy-network" to all services, and potentially a link to the documentations for docker-compose domain: https://docs.dokploy.com/docs/core/docker-compose/domains, e.g. alongside the blue highlight note below:
    ![Screenshot 2025-01-08 at 10 08 28 am](https://github.com/user-attachments/assets/348f9700-ccc9-4b40-9191-80d08c695572)

I think option 3 is probably the right approach.

**Comment by Siumauricio** [comment]
I agree, I think we should manage a toggle that automatically says if we want to add to all services the dokploy-network so it would automatically do everything and by default it would be enabled!

**Reply by nktnet1** [reply]
Not completely against this (I also think option 1 is more convenient than 2), although this would mean the databases of all services are visible to all other services within Dokploy network.

This could be a problem across different services/projects, especially if they're managed by different users/team.

I think creating a private/internal network for each compose file, with an option to enable Dokploy network, is a good middleground?

**Comment by depado** [comment]
I just spent literal hours trying to figure out what was going on for umami. Thank you.

**Reply by djsisson** [reply]
i would slightly alter the above approach, 

instead of dumping everything in the dokploy-network

you instead add your own network in the compose such that you keep your db and other services isolated, and only add your ingress service into the dokploy-network, so that traefik has access to it.
This also helps with conflicting services names, since a lot of services use repeat names like postgres/db/redis etc

**Reply by depado** [reply]
Could you show an example on how you would achieve that? Won't that clash with the networks being added by dokploy itself?

**Reply by nktnet1** [reply]
@depado I believe @djsisson is suggesting that you create another bridge network shared only between your compose services (e.g. umami and db), then only expose your umami service to the external dokploy-network.

Note however that with the introduction of isolated deployment (context: #1004), this is effectively resolved.

**Reply by depado** [reply]
That feature isn't available for git fetched compose files though but thanks for the heads up :+1: 
I'll have a try with a specific network instead of reusing the `dokploy-network` :smile:

**Reply by nktnet1** [reply]
No worries :)

Just on Umami - here's an example:

```yaml
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DATABASE_TYPE: postgresql
      APP_SECRET: ${APP_SECRET}
    networks:
      - internal-net
      - dokploy-network

  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - 9123:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - internal-net

volumes:
  db-data:

networks:
  internal-net:
    driver: bridge
  dokploy-network:
    external: true
```

Hope it helps.
