### DISCUSSION TITLE
Getting CouchDB running on Dokploy

### DISCUSSION THREAD

**Discussion by SlavenIvanov** [Dokploy/dokploy#1074] [Q&A] [answered]
Hello! I would like to get CouchDB working on Dokploy(and potentially submitting a template PR if the maintainers are ok with that), but I don't know where to start. Can someone point me in the right direction?

**Comment by Blankeos** [comment]
Following this since I'm also wondering how to host an alternative database other than MySQL, MariaDB, PostgreSQL. (e.g. SQLite).
I did check the Projects > "Templates" though. Since Pocketbase is possible (uses SQLite under the hood) , I'm guessing it's possible to run a database as an "Application" maybe?

Actually now that I think about it, maybe you can also check how Templates are added.

**Comment by Siumauricio** [comment, marked as answer]
Yes, we are open to accept any PR, for many people who don't know, it is feasible and advisable to separate a docker compose and structure it in applications.




```yaml
services:
  app:
    image: dokploy/dokploy:latest
    ports:
      - 3000
 backend:
    image: dokploy/backend:latest
    ports:
      - 3000
 ```
 
this easily becomes:

2 Applications

1 for the app and the other for the backend, what is the difference? In docker compose we can handle many applications in a single file, while applications are treated as a single entity and not multiple, so we need to separate them.

you can use this template for cockroachdb

```yaml
version: '3.8'

services:
  cockroach:
    image: cockroachdb/cockroach:v23.2.0
    command: start-single-node --insecure
    ports:
      - "26257"
      - "8080" 
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    environment:
      COCKROACH_MAX_OPEN_FILES: 1024
    restart: unless-stopped

volumes:
  cockroach-data:
    driver: local
 ```
 In Domains
![Screenshot 2025-01-10 at 12 30 33 AM](https://github.com/user-attachments/assets/738ef915-e9dd-4882-893f-11be082d2cb1)


when you deploy you can access to the dashboard
![Screenshot 2025-01-10 at 12 30 50 AM](https://github.com/user-attachments/assets/a845410e-1799-4ba0-9117-f6a0ac76ea7f)

Regarding how to contribute you can read here: https://github.com/Dokploy/dokploy/blob/canary/CONTRIBUTING.md#templates
