### DISCUSSION TITLE
API key authentication using a custom header

### DISCUSSION THREAD

**Discussion by chai3** [Dokploy/dokploy#1380] [Q&A]
I want to add API key authentication using a custom header to my app.
It's not basic authentication.
I don't want to modify the app's source code
I tried modify application traefik and reload treafik but could not add authentication.

```
http:
  routers:
    testpj-mywhoami-jer9lp-router-1:
      rule: Host(`192.168.1.23`)
      service: testpj-mywhoami-jer9lp-service-1
      middlewares: []
      entryPoints:
        - web
  middlewares:
    test-apikey:
      plugin:
        apiKey:
          secretParam = "mysecretheader"
          secretValue = "$2y$05$W8revhHpKlbH1UfCzpR0He/dK9mjXZRLjfq5RkYZKU7//EUrWz3lG"
          kind = "header"
  services:
    testpj-mywhoami-jer9lp-service-1:
      loadBalancer:
        servers:
          - url: http://testpj-mywhoami-jer9lp:80
        passHostHeader: true
```

Do you have any advice?

### reference
- https://doc.traefik.io/traefik-enterprise/middlewares/apikey/
