### DISCUSSION TITLE
Mount files but not in files directory

### DISCUSSION THREAD

**Discussion by hamidhaghdoost** [Dokploy/dokploy#1407] [Q&A]
I have a Docker Compose file with two different projects inside—let's say `front` and `back`. I want to mount the `./front/.env` and `./back/.env` files inside their respective containers.

The codebase is already in place, and I cannot change its structure. I want to know if there is flexibility in defining the mount path in general, not just within the `files` folder.

Here’s a sample `docker-compose.yml` file:

```yaml
services:
  back:
    ...
    env_file:
      - ./back/.env 

  front:
    ...
    env_file:
      - ./front/.env 
```

Thanks!
