### DISCUSSION TITLE
HTTPS app uses http resources

### DISCUSSION THREAD

**Discussion by RxDeveloper** [Dokploy/dokploy#1496] [General]
Hi there,

I tried to deploy a couple of Docker Compose app. They deployed just fine but they don't work as expected.

Example: Zitadel:

```yml
services:
  zitadel:
    restart: 'always'
    networks: 
      - dokploy-network
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "${ZITADEL_MASTER_KEY}" --tlsMode disabled'
    environment:
      ZITADEL_EXTERNALDOMAIN: auth.mydomain.com
      ZITADEL_EXTERNALSECURE: true
      ZITADEL_TLS_ENABLED: false
      ZITADEL_EXTERNALPORT: 443
      ZITADEL_DATABASE_POSTGRES_HOST: ${PG_HOST}
      ZITADEL_DATABASE_POSTGRES_PORT: ${PG_PORT}
      ZITADEL_DATABASE_POSTGRES_DATABASE: ${PG_DB}
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: ${PG_USER}
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: ${PG_PASS}
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: ${PG_ADMIN_PASS}
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable

networks:
  dokploy-network:
    external: true
```

<img width="705" alt="image" src="https://github.com/user-attachments/assets/11594a73-c3d3-4a73-a819-bbbd63c921ee" />

I added necessary A record to my DNS (Cloudflare). I can access the login page but after login, management console doesn't load like this.

<img width="1337" alt="image" src="https://github.com/user-attachments/assets/ec928820-d862-4497-a281-8d5398876923" />

As you can see, I try to enter from the `https://auth...` URL but it tries to make request from `http://auth...` 

I experienced same thing with Keycloak deployment as well. What am I missing?
