### DISCUSSION TITLE
shm-size for dokploy database service Postgresql. How increase? ⚠️

### DISCUSSION THREAD

**Discussion by vksee** [Dokploy/dokploy#1538] [Q&A]
VACUUM ANALYZE;
SQL Error [53100]: ERROR: could not resize shared memory segment "/PostgreSQL.228052640" to 67128768 bytes: No space left on device

Now:
Docker version 27.5.1, build 9f9e405

docker exec -it 69f3619c338e df -h /dev/shm
```
Filesystem                Size      Used Available Use% Mounted on
shm                      64.0M      2.0M     62.0M   3% /dev/shm
```

How fix: need to resize shm-size for docker container.
--shm-size=128mb

What can I do to continue using the builtin dokploy Postgresql service?

**Comment by vksee** [comment]
Dokploy database serive Postgresql.
Advanced Settings -> Command.

Is it possible to set a replacement for command docker run?
If so, can someone give an example of a command that is correct for this case.

**Comment by avasilic** [comment]
@vksee did you manage to figure it out

**Comment by vksee** [comment]
@avasilic 

At that time, there was such a decision:
change the limit on the host.

**/etc/docker/daemon.json**
```
{
   "default-shm-size" : "128M"
}
```

**Comment by vksee** [comment]
As a result: a docker compose project for PostgreSQL was created for the server managed by Dokploy.

Example, deployed from source code,
shared_buffers = 2GB
Host memory >= 8Gb

```yaml
version: '3.8'

services:

  postgres:
    image: postgres:16.10-alpine
    volumes:
      - ../files/postgresql_data/:/var/lib/postgresql/data/
      - ./.docker/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    shm_size: 2g
    command: 
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    restart: always
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
```
