### DISCUSSION TITLE
Suggestion: LiteLLM Support in Templates

### DISCUSSION THREAD

**Discussion by muhmd101** [Dokploy/dokploy#1545] [Ideas]
Hey Dokploy team,

I was checking out your templates [Dokploy Templates](https://templates.dokploy.com) and had an idea. I think it would be awesome if you added a template for [LiteLLM](https://litellm.ai). It's a really handy tool that makes it super easy to work with different AI models like OpenAI, Anthropic, and Cohere – you just use one API!

For Dokploy users, this could be a game-changer because:

*   Building and deploying AI stuff would be way simpler.
*   Switching between AI providers would be a breeze.
*   LiteLLM can even help save some money on API costs.

I've actually gotten LiteLLM running on Dokploy myself, and it works great!  So, I'm pretty sure a template showing how to set it up would be a huge help to other users.  It'd make integrating LLMs with Dokploy really quick and straightforward.

Just a thought!

**Comment by Siumauricio** [comment]
Hey, thanks for the explanation, if you want to add this template you can follow the instructions here https://github.com/Dokploy/templates?tab=readme-ov-file#how-to-add-a-new-template

**Comment by sanjibnarzary** [comment]
Got litellm working in dokploy today after several hours of trial and error
1. Make a `litellm_config.yaml` lets say in home folder `/home/seekgpt/litellm_config.yaml` in the host computer

```
model_list:
  - model_name: "llama3.2"             
    litellm_params:
      model: "ollama/llama3.2"
      api_base: "http://localhost:11434"
general_settings: 
  master_key: sk-123456
  database_url: "postgresql://postgres:postgres@postgres:5432/litellm"
```

2. Create a docker compose application in project section of dokploy dashboard

```
services:
    litellm:
        volumes:
            - /home/seekgpt/litellm_config.yaml:/app/config.yaml
        environment:
            - AZURE_API_KEY=d6***********
            - AZURE_API_BASE=https://openai-***********/
        ports:
            - 4000:4000
        image: ghcr.io/berriai/litellm:main-latest
        command: --config /app/config.yaml --detailed_debug
```
3. Set envs
```
LITELLM_MASTER_KEY="sk-123456" # Your master key for the proxy server. Can use this to send /chat/completion requests etc
LITELLM_SALT_KEY="sk-123456" # Can NOT CHANGE THIS ONCE SET - It is used to encrypt/decrypt credentials stored in DB. If value of 'LITELLM_SALT_KEY' changes your models cannot be retrieved from DB
DATABASE_URL="postgresql://postgres:postgres@postgres:5432/litellm" # Need a postgres database? (Check out Supabase, Neon, etc)
## OPTIONAL ##
PORT=4000 # DO THIS FOR RENDER/RAILWAY
STORE_MODEL_IN_DB="True" # Allow storing models in db
```
4. Deploy
5. Visit localhost:4000/ui for admin
