### DISCUSSION TITLE
after deploy custom compose app , custom domain don't point to the correct port.

### DISCUSSION THREAD

**Discussion by Nicj228** [Dokploy/dokploy#1693] [General]
### To Reproduce

1-deploy custom compose app
2-add custom domain point to port ex:3000
3 - Attempt to access the services through domain.

### Current vs. Expected behavior

after deploy custom compose app , custom domain don't point to the correct port. so the app is not accessible via mydomain.com but accessible at mydomain.com:xxx

### Provide environment information

```bash
Version v0.21.4
```

### Which area(s) are affected? (Select all that apply)

Traefik

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

No

**Comment by daraeowl** [comment]
I'm having the same problem, I'm using nixpacks to build our project and it always exposes it like this 


> tl-guildmanager@0.1.0 start /app
> next start -p 3001
▲ Next.js 15.2.4
- Local:        http://localhost:3001
- Network:      http://10.0.0.5:3001
✓ Starting...
✓ Ready in 383ms
(node:20) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

the public ip is not accesible, not even through domain since the port mapping is not working. 

I've tried the latest version and the Version v0.21.2

**Comment by Siumauricio** [comment]
Please share some docker compose to test, as we currently have more than 160 templates running so I don't think it's a fluke, read here when having troubles with domain on docker compose https://docs.dokploy.com/docs/core/troubleshooting#docker-compose-domain-not-working

**Comment by Nicj228** [comment]
version: '3.8'
services:
  popspace:
    image: ghcr.io/with-labs/popspace:latest
    environment:
      DATABASE_URL: file:/data/db.sqlite?connection_limit=1
      UNICORN_DATABASE_URL: /data/unicorn.sqlite
      USER_FILES_DIRECTORY: /data/user-files
      WALLPAPERS_DIRECTORY: /data/wallpapers
      PUBLIC_URL: http://localhost:8889
    ports:
      - '8888:8888'
      - '8889:8889'
      - '8890:8890'
      - '8891:8891'
    volumes:
      - popspace_data:/data
    labels:
      - traefik.http.routers.projets-call-ylb7ry-26-web.rule=Host(`projets-call-ylb7ry-6cb4e6-44-200-85-14.traefik.me`)
      - traefik.http.routers.projets-call-ylb7ry-26-web.entrypoints=web
      - traefik.http.services.projets-call-ylb7ry-26-web.loadbalancer.server.port=8888
      - traefik.http.routers.projets-call-ylb7ry-26-web.service=projets-call-ylb7ry-26-web
      - traefik.enable=true
    networks:
      - dokploy-network
volumes:
  popspace_data: null
networks:
  dokploy-network:
    external: true

**Comment by Nicj228** [comment]
but it work correctly when i deploy a template service.

**Comment by Siumauricio** [comment]
This seems more like a question, let's move it to discussions.

**Comment by rek3000** [comment]
Sorry for necro-bump. 
I got exact same problem
```
services:
  proxy:
    image: ubuntu/squid:5.2-22.04_beta
    env_file:
      - .env
    ports:
      - 3128
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
      - ./scripts/squid-entrypoint.sh:/docker-entrypoint.d/10-squid-entrypoint.sh:ro
      - squid_log:/var/log/squid
      - squid_cache:/var/spool/squid
    environment:
      - PROXY=${PROXY}
    entrypoint:
      - /bin/sh
      - /docker-entrypoint.d/10-squid-entrypoint.sh
    networks:
      - dokploy-network
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.predarbovh-compose-o2kyfb-100-web.rule=Host(`predarbovh-compose-o2kyfb-dcec9f-51-222-206-58.traefik.me`)
      - traefik.http.routers.predarbovh-compose-o2kyfb-100-web.entrypoints=web
      - traefik.http.services.predarbovh-compose-o2kyfb-100-web.loadbalancer.server.port=32926
      - traefik.http.routers.predarbovh-compose-o2kyfb-100-web.service=predarbovh-compose-o2kyfb-100-web
      - traefik.enable=true
```

This was supposed to be exposed in 3128 port. However, it is changed each time i redeployed 

`4ac9582448b3   ubuntu/squid:5.2-22.04_beta                 "/bin/sh /docker-ent…"   24 minutes ago   Up 24 minutes   0.0.0.0:32936->3128/tcp, :::32936->3128/tcp   `
