### DISCUSSION TITLE
How to connect to deployed app via localhost?

### DISCUSSION THREAD

**Discussion by erikdemarco** [Dokploy/dokploy#1748] [General]
I'm deploying a dockered redis/dragonfly. how to connect to this app via same server?

**Comment by Siumauricio** [comment]
What are you using docker compose or applications based?

**Reply by itsneeku** [reply]
Hey sorry for the necropost, but I'm facing the same issue with dragonfly (a redis alternative)
I'm running it as a docker compose. I've tried assigning it a domain but no luck.

```
version: '3.8'
services:
  dragonflydb:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
    environment: 
      - DFLY_requirepass
volumes:
  dragonflydata:
  ```
  
  The current template assigns a traefik domain on the correct port as HTTP,  but same issue
