### DISCUSSION TITLE
How can I achieve the redirect / proxy feature from netlify?

### DISCUSSION THREAD

**Discussion by chrisjung-dev** [Dokploy/dokploy#1789] [Q&A]
I use an App on netlify, using the redirects feature to simplify CORS and 'hide' the real API URL on a different server via the redirects feature from netlify.

```toml
[[redirects]]
  from = "/api/*"
  to = "https://[my-api-host]/:splat"
  force = true
  status = 200
```

How can I achieve this in dokploy?

PS: I am aware of the topic in the docs, tried different times and configs.
