### DISCUSSION TITLE
Select/Change host in swarm mode?

### DISCUSSION THREAD

**Discussion by m1212e** [Dokploy/dokploy#1861] [Q&A]
Hi,

is it possible to manually change/select the host of a container when running in swarm mode?
E.g. I have a postgres created and would like to bring it and its data to another physical device. Can I somehow do that?
Also: Can I select a physical drive location for a docker drive?

Thanks a lot for your work!

**Comment by Siumauricio** [comment]
I don't have much knowledge of this, could you give me an example with commands, so I can determine if it is possible?

**Reply by m1212e** [reply]
I'll give you a docker-compose example for deployment with a swarm/stack:

```yml
services:
  jellyfin:
    image: jellyfin/jellyfin
    user: 1002:1001
    volumes:
      - jellyfin-config:/config
      - jellyfin-media:/media
    environment:
      - TZ=Europe/Berlin
    networks:
      - default
      - traefik_traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.mydomain.com`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.id == jcviuob68zc2ntzc0x9gipdj9

volumes:
  jellyfin-config:
    driver: local
    driver_opts:
      type: nfs
      o: vers=4,addr=192.168.188.118,rw
      device: ":/mnt/chongus/nfsshare/data/services/jellyfin/config"
  jellyfin-media:
    driver: local
    driver_opts:
      type: nfs
      o: vers=4,addr=192.168.188.118,rw
      device: ":/mnt/chongus/nfsshare/data/services/jellyfin/media"

networks:
  traefik_traefik:
    external: true
```

See the deployment section? This forces the container to be only deployed to nodes where the ID matches which in turn equals to: Only run on this node.

Regarding the physical drive: To determine where a docker volume is stored and to make it available across a swarm, volume drivers might be helpful: https://docs.docker.com/engine/storage/volumes/#use-a-volume-driver
My thought behind this was, that it might change over time where I want data to be stored. Say I slowly reach the storage limit of my drive. I get a new machine with a larger drive, hook it into the dokploy swarm and then want all my data to be transferred to that machine. Something like that would be awesome!
