### DISCUSSION TITLE
How to enable traefik metrics in dokploy?

### DISCUSSION THREAD

**Discussion by ItsNaazanin** [Dokploy/dokploy#1876] [Q&A] [answered]
How to enable Traefik metrics in Dokploy?

**Comment by nktnet1** [comment]
If you're referring to how to enable the Traefik Dashboard, see #696

**Reply by ItsNaazanin** [reply, marked as answer]
I'm asking about Traefik metrics. I just did it adding this to traefik.yml:
```
entryPoints:
  metrics:
    address: :8082

metrics:
  prometheus:
    entryPoint: metrics
```
