### DISCUSSION TITLE
Unwanted port mapping to 0.0.0.0

### DISCUSSION THREAD

**Discussion by ItsNaazanin** [Dokploy/dokploy#1879] [Q&A] [answered]
I'm using Docker Registry Template from Dokploy, it goes by:
```
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000
    volumes:
      - ../files/auth/registry.password:/auth/registry.password
      - registry-data:/var/lib/registry
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: true
      REGISTRY_HEALTH_STORAGEDRIVER_ENABLED: false
      REGISTRY_HTTP_SECRET: ${REGISTRY_HTTP_SECRET}
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password

volumes:
  registry-data:
  ```
As you can see there is no port mapping here, but I have this in `docker ps | grep registry`:
  
![image](https://github.com/user-attachments/assets/327bd0dc-eed1-4c87-9782-fd55c06e0e7f)

Same issue goes for Bugsink:
![image](https://github.com/user-attachments/assets/15716843-a425-4d85-ae69-5aa6b6e39d27)
How can I prevent this?
