### DISCUSSION TITLE
Does Dokploy support wildcard subdomains and custom domain routing?

### DISCUSSION THREAD

**Discussion by cunpingtai** [Dokploy/dokploy#2057] [Q&A] [answered]
Hi, I have an application that allows users to configure custom subdomains (like user1.example.com) or custom domains (like userdomain.com) to access specific content in my app.

My current plan is:
	1.	Configure a wildcard domain (e.g., *.example.com) in Dokploy’s domain settings.
	2.	In DNS:
	•	Use an A record to point all subdomains to my app server.
	•	Use CNAME records to point custom domains to my main domain (e.g., example.com).

The goal is for all these domains to route correctly to my app and serve the appropriate content based on the hostname.

Is this setup supported in Dokploy? And is this a reasonable and feasible approach?

Thanks!

**Comment by djsisson** [comment, marked as answer]
@cunpingtai afaik dokploy only uses Host rules not HostRegexp so i think you will have to add your own dynamic file

```yaml
http:
  routers:
    myapp-router:
      entryPoints:
        - web
        - websecure
      rule: "HostRegexp(`^([a-z0-9-]+)\\.example\\.com$`)"
      service: myapp-service
      tls: {}

  services:
    myapp-service:
      loadBalancer:
        servers:
          - url: "http://myapp:3000"
```

'myapp' needs to match the service name in your compose, add any middleware or alter tls settings as required, this matches all subdomains on example.com

**Comment by Siumauricio** [comment]
Dokploy is simply a wrapper over traefik, so the question would be traefik supports wildcard subdomains? the answer is yes, here in the traefik documentation it mentions the use of HostRegex https://doc.traefik.io/traefik/routing/routers/#host-and-hostregexp, so you would have to add it manually to your application configuration found in advanced section -> traefik configuration

**Reply by terion-labs** [reply]
> application configuration found in advanced section -> traefik configuration

but there is no "traefik configuration" in project's advanced settings...

**Reply by terion-labs** [reply]
<img width="2232" height="3350" alt="screencapture-dashboard-project-Q0gMoiZtMXyzviPf4F-zP-environment-W-fRaLWKmaTSds5dbbLc-services-compose-OMvhyXyvRPXbYbdLDA11M-2026-03-13-22_22_45" src="https://github.com/user-attachments/assets/fa8336dd-6902-42f6-b071-e667c915a5e5" />

**Comment by smcalilly** [comment]
I was able to get it setup with something like this:
```
http:
  routers:
    <app>-wildcard-router:
      rule: HostRegexp(`^([a-z0-9-]+)\.example\.com$`)
      service: <app>-service
      entryPoints:
        - web
        - websecure
      tls:
        options: {}
  services:
    <app>-service:
      loadBalancer:
        servers:
          - url: http://<docker-service-name>:<server-port>
        passHostHeader: true
```

And it's using an origin certificate that I uploaded in the UI. 


Some things to note:
- don't add a domain in the UI
- if you were like me and tried using Let's Encrypt first, then you might need to clean some config up in the traefik files. Go to `Remote Servers` > `Actions` > `Show Traefik File System`.
