### DISCUSSION TITLE
How to attach docker secrets?

### DISCUSSION THREAD

**Discussion by bautrukevich** [Dokploy/dokploy#207] [Q&A]
Hello! I have a secrets section in my docker compose file.

```
version: "3.9"
services:
  api:
    image: ${REGISTRY}/edkraft-api-${BRANCH}:${IMAGE_TAG}
    volumes:
      - ./:/app
    depends_on:
      - php-fpm
    networks:
      - dokploy-network
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`dev-api.edkraft.app`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.services.api.loadbalancer.server.port=80

  php-fpm:
    image: ${REGISTRY}/edkraft-php-fpm-${BRANCH}:${IMAGE_TAG}
    environment:
      YII_ENV: ${YII_ENV}
      YII_DEBUG: ${YII_DEBUG}
      APP_NAME: ${APP_NAME}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_SECRET_KEY: ${APP_SECRET_KEY}
      APP_TIMEZONE: ${APP_TIMEZONE}
      APP_FRONTEND_DOMAIN: ${APP_FRONTEND_DOMAIN}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME: ${DB_NAME}
      JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
    volumes:
      - ./:/app
    secrets:
      - db_password
      - jwt_encryption_key
      - jwt_public_key
      - jwt_private_key
    env_file:
      - .env
    networks:
      - dokploy-network

  php-cli:
    image: ${REGISTRY}/edkraft-php-cli-${BRANCH}:${IMAGE_TAG}
    environment:
      YII_ENV: ${YII_ENV}
      YII_DEBUG: ${YII_DEBUG}
      APP_NAME: ${APP_NAME}
      APP_DOMAIN: ${APP_DOMAIN}
      APP_SECRET_KEY: ${APP_SECRET_KEY}
      APP_TIMEZONE: ${APP_TIMEZONE}
      APP_FRONTEND_DOMAIN: ${APP_FRONTEND_DOMAIN}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME: ${DB_NAME}
      JWT_ENCRYPTION_KEY_FILE: /run/secrets/jwt_encryption_key
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
    volumes:
      - ./:/app
    secrets:
      - db_password
      - jwt_encryption_key
      - jwt_public_key
      - jwt_private_key
    env_file:
      - .env
    networks:
      - dokploy-network

secrets:
  db_password:
    file: ./files/secrets/staging/db_password
  jwt_encryption_key:
    file: ./files/secrets/staging/jwt_encryption_key
  jwt_public_key:
    file: ./files/secrets/staging/jwt_public_key
  jwt_private_key:
    file: ./files/secrets/staging/jwt_private_key
  aws_secret_access_key:
    file: ./files/secrets/staging/aws_secret_access_key

networks:
  dokploy-network:
    external: true
``` 

How to attach them correct? I was trying to mount but all the time its failing.

`open /etc/dokploy/compose/platform-dev-586727/files/secrets/staging/db_password: no such file or directory`

**Comment by Siumauricio** [comment]
Hi, 

I think that instead of `./files/secrets` it should be `./secrets....`

Example:

```
version: '3.8'

services:
  meilisearch:
    networks:
      - dokploy-network
    image: getmeili/meilisearch:v1.8.3
    ports:
      - ${MEILISEARCH_PORT}
    volumes:
      - meili_data:/meili_data
    environment:
      MEILI_MASTER_KEY: /run/secrets/meili_master_key
      MEILI_ENV_FILE: /run/secrets/meili_env
    labels:
      - traefik.enable=true
      - traefik.http.routers.${HASH}.rule=Host(`${MEILISEARCH_HOST}`)
      - traefik.http.services.${HASH}.loadbalancer.server.port=${MEILISEARCH_PORT}

volumes:
  meili_data:
    driver: local
networks:
  dokploy-network:
    external: true

secrets:
  meili_master_key:
    file: ./secrets/meili_master_key.txt
  meili_env:
    file: ./secrets/meili_env.txt
```

And in the volumes section i defined...:

![Screenshot 2024-07-12 at 2 02 15 AM](https://github.com/user-attachments/assets/1fc8fa44-b5b4-4957-9785-2e11e7cb0f6a)

You can also check the filesystem to see the route of the secrets
![Screenshot 2024-07-12 at 2 03 46 AM](https://github.com/user-attachments/assets/b3b46529-6ab9-4994-adb8-f7fc9912dce3)
