### DISCUSSION TITLE
How can i configure Internal Host for Applications?

### DISCUSSION THREAD

**Discussion by joetifa2003** [Dokploy/dokploy#405] [Q&A]
I saw in the docs that I can specify an internal host/port to connect to the database.

How can I do the same thing for Applications?

For example, if I have a service that I don't want to expose to the public, but I want other services to see it, how can I connect them?

Is it by the App name field when I create the service, when I tried to create services with an existing app name, it didn't error out, so this cannot be possible.

And when I open a service I see, which I guess, is the container name like this foo-9asdas...

Can i connect to the service by using host `https://foo-9asdas:<PORT>`

**Comment by joetifa2003** [comment]
I think this should be added to the docs.

**Comment by Siumauricio** [comment]
By default every application/database comes with a hostname which is next to the name of the application usually is something like 
 `projectName-applicationName-${HASH}`


![image](https://github.com/user-attachments/assets/0de31a1d-65b5-4b69-9aba-4c2b9332dcc3)

This is what we do to for domain mapping
![Screenshot 2024-09-02 at 12 01 17 PM](https://github.com/user-attachments/assets/26785f65-829d-43bc-82ad-9fb1548b471a)

**Reply by joetifa2003** [reply]
Thank you!

I did try to do a curl from the container terminal and it seems to be working (same port as the domain), I didn't need to do any configuration change.

So by default i can access any port in the container, without publish/exposing the ports to the public?

Also, can you point to me some doc related to this?

**Comment by girorme** [comment]
@Siumauricio Hello!

We've created a service using Dockerfile (branch deploy) and configured a Traefik domain, and the configuration in the advanced tab was generated correctly. However, it's not working (just getting a 404 error). Is there any additional configuration needed in this case?

Here's the generated YAML:

```yaml
# fake values
http:
  routers:
    test-router:
      rule: >-
        Host(`test-domain.traefik.me`)
      service: test-service
      middlewares: []
      entryPoints:
        - web
  services:
    test-service:
      loadBalancer:
        servers:
          - url: http://test-host:3000
        passHostHeader: true
```

Additionally, we've created a domain using an A record in DNS, but it still doesn't work. (Using docker-compose services works perfectly with "labels" configuration)

Thanks in advance
