### DISCUSSION TITLE
Compose env variables

### DISCUSSION THREAD

**Discussion by fordnox** [Dokploy/dokploy#445] [Q&A]
I have raw compose:

I need to pass `TEXT=Hello` from env variables, how can i do that?

```
services:
  echo:
    image: hashicorp/http-echo
    networks:
      - dokploy-network
    command:
      - -listen=:8086
      - -text=${TEXT}
    ports:
      - 8086:8086
    labels:
      - traefik.enable=true
      - traefik.http.routers.echo.rule=Host(`echo.example.com`)
      - traefik.http.routers.echo.entrypoints=web
      - traefik.http.services.echo.loadbalancer.server.port=8086
networks:
  dokploy-network:
    external: true

 ```
 
This **does not** replace the value
<img width="867" alt="Screenshot 2024-09-12 at 18 59 58" src="https://github.com/user-attachments/assets/b107de42-24f4-4bf8-9be6-ceccb1b89dce">
