### DISCUSSION TITLE
Add traefik label traefik.docker.network when domain created

### DISCUSSION THREAD

**Discussion by vanex97** [Dokploy/dokploy#609] [Ideas]
I encountered a gateway timeout issue, and after a long search, I resolved it by specifying the label:

`- traefik.docker.network=dokploy-network`

Why not add this parameter automatically when creating domains?

Here’s the configuration:

```
nginx:
    image: nginx:1.27.1-alpine
    restart: unless-stopped
    volumes:
        - .:/var/www
        - storage-data:/var/www/storage
        - ./docker/storage_app:/var/www/storage/app
        - ./docker/nginx/logs:/var/log/nginx/
        - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - app
    networks:
        - dbm-nginx-network
        - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
```
