### DISCUSSION TITLE
How to add a resources section in advanced if I'm using docker-compose ?

### DISCUSSION THREAD

**Discussion by artem-kostylev** [Dokploy/dokploy#667] [General]
How to add a resources section in advanced if I'm using docker-compose to run Elasticsearch?

my config:

<img width="632" alt="image" src="https://github.com/user-attachments/assets/2d474400-9870-4beb-a741-e6be36da86a0">

**Comment by Siumauricio** [comment]
Can you try this?

```yaml
deploy:
  resources:
    limits:
      cpus: '0.001'
      memory: 50M
```

Reference:
https://stackoverflow.com/questions/42345235/how-to-specify-memory-cpu-limit-in-docker-compose-version-3
