### DISCUSSION TITLE
How to access Traefik dashboard after enabling it?

### DISCUSSION THREAD

**Discussion by LickABrick** [Dokploy/dokploy#696] [Q&A] [answered]
I have enabled the Traefik dashboard via the settings:
![image](https://github.com/user-attachments/assets/38d29a84-db5a-407f-b79c-b69e5b9162ad)

But how/where do I access it?

**Comment by Siumauricio** [comment, marked as answer]
Your ip:8080

**Reply by nktnet1** [reply]
Adding to this, if you have a custom domain, you can serve your traefik dashboard there using similar steps to Coolify:
- https://coolify.io/docs/knowledge-base/traefik/dashboard

---

1. Make sure you are in your VPS, e.g.
    ```sh
    ssh VPS_USER@VPS_IP_ADDRESS    # Replace values
    ```

2. Generate a new user/password pair using htpasswd, e.g.
    ```sh
    sudo apt update
    sudo apt-get install apache2-utils
    htpasswd -nbB USERNAME PASSWORD    # Replace values
    ```

3. Open an extra file in your traefik dynamic directory with a text editor, e.g.
    ```sh
    sudo vim /etc/dokploy/traefik/dynamic/dashboard.yml    # Can replace `vim` with `nano`
    
4. Paste in the template below (from coolify instructions), replacing all values (i.e. your domain, and the generated output from the previous htpasswd command)
    ```yaml
    http:
      routers:
        dashboard:
          rule: Host(`<DOMAIN_FOR_TRAEFIK>`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
          service: api@internal
          tls:
            certResolver: letsencrypt
          middlewares:
            - auth
      middlewares:
        auth:
          basicAuth:
            users:
              - "<GENERATED_USERNAME>:<GENERATED_PASSWORD>"

    ```
    
 5. Access your dashboard at the new URL (pick one of HTTP/HTTPS as appropriate):
     - http://<DOMAIN_FOR_TRAEFIK>/dashboard/#/
     - https://<DOMAIN_FOR_TRAEFIK>/dashboard/#/

---

# UPDATE 2025-02-03

If you want to also redirect the root domain to `/dashboard/#/` automatically (instead of showing 404), you can do it as follows in your `dashboard.yml` (make sure to update the domain and <GENERATED_HASH> password):

## HTTPS Example

```yaml
http:
  routers:
    dashboard:
      rule: Host(`traefik.example.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      service: api@internal
      tls:
        certResolver: letsencrypt
      middlewares:
        - auth
    redirect-root:
      rule: Host(`traefik.example.com`) && Path(`/`)
      entryPoints:
        - websecure
      middlewares:
        - redirect-to-dashboard
      service: noop@internal
  middlewares:
    auth:
      basicAuth:
        users:
          - "<GENERATED_HASH>"
    redirect-to-dashboard:
      redirectRegex:
        regex: "^https?://traefik\\.example\\.com/?$"
        replacement: "https://traefik.example.com/dashboard/#/"
        permanent: true
```

## HTTP Example (e.g. when using cloudflare tunnel)

```yaml
http:
  routers:
    dashboard:
      rule: Host(`traefik.example.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      service: api@internal
      middlewares:
        - auth

    redirect-root:
      rule: Host(`traefik.example.com`) && Path(`/`)
      entryPoints:
        - web
      middlewares:
        - redirect-to-dashboard
      service: noop@internal

  middlewares:
    auth:
      basicAuth:
        users:
          - "<GENERATED_HASH>"

    redirect-to-dashboard:
      redirectRegex:
        regex: "^https?://traefik\\.example\\.com/?$"
        replacement: "https://traefik.example.com/dashboard/#/"
        permanent: true
```
