### DISCUSSION TITLE
How would I install Home Assistant?

### DISCUSSION THREAD

**Discussion by Asleep123** [Dokploy/dokploy#730] [Q&A]
Title says it all. It’s more than just a simple docker pull and run, and I’m not sure how I would setup traefik with it. I think you need to do it a certain way or you lose some features because you aren’t using their official HA OS. I also plan on using CF tunnels as it’s a home server, I don’t want to open anything.

**Comment by mcasaccio** [comment]
How can I use Cloudflare tunnel? I can connect to the tunnel to the dokploy but I can't connect to another server that also has a tunnel.

**Comment by nktnet1** [comment]
> I’m not sure how I would setup traefik with it. I think you need to do it a certain way or you lose some features because you aren’t using their official HA OS

What kind of feature do you lose? I'm not a big user of home assistant (only use it for basic things like lights & TVs), but this simple compose works fine for my use case:

```yaml
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      # Don't forget to create the config in your host machines and tweak them accordingly
      - /opt/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    ports:
      - 8123:8123
    restart: unless-stopped
```

---

> I also plan on using CF tunnels as it’s a home server, I don’t want to open anything.

I left some pointers on Cloudflare Tunnel here:
- https://github.com/Dokploy/dokploy/discussions/966#discussioncomment-11664079

Not too difficult to set up, just need to be wary of the caveats.
