### DISCUSSION TITLE
How to add basic authentication to an application?

### DISCUSSION THREAD

**Discussion by empz** [Dokploy/dokploy#800] [Q&A]
This doc page says there's an Advanced option to set some basic authentication for an appilcation, but I cannot seem to find anywhere on my Dokploy UI.

https://docs.dokploy.com/docs/core/applications/advanced#security

**Comment by kerimovok** [comment]
Maybe you are using Compose type, you should use Application type for these things.
https://github.com/Dokploy/dokploy/discussions/791#discussion-7584631

**Reply by empz** [reply]
I'm using an existing template, which is based on Compose.

**Reply by kerimovok** [reply]
If it is your compose files, you can use traefik labels, if it is a template from dokploy, I don't really know

https://doc.traefik.io/traefik/middlewares/http/basicauth/

**Reply by Siumauricio** [reply]
you are looking at applications documentation which is very different from compose

**Reply by empz** [reply]
I'm using an application from the built-in templates which seems to be based on the Compose type. Does that mean there's no way to add basic auth to a Compose-based application?

**Reply by kerimovok** [reply]
Templates just paste docker-compose config into the raw tab, so you can basically modify it to add traefik labels.
https://doc.traefik.io/traefik/middlewares/http/basicauth/

Something like this
```yaml
version: "3.8"
services:
  service:
    image: ...
    volumes: ...
    # ========== Traefik Labels ========== 
    labels:
          - "traefik.http.middlewares.service-auth.basicauth.users=user:hashedpassword"
          - "traefik.http.routers.service.middlewares=service-auth"
```

To hash password
```bash
htpasswd -nb user strongpassword
```
Output
```bash
user:$apr1$xyz$Kp.WKOrvnYjRUdjHp9e7W/
```
