### DISCUSSION TITLE
Bind mounts with compose

### DISCUSSION THREAD

**Discussion by Eliophot** [Dokploy/dokploy#878] [Q&A]
Hello,

I try this compose

```
services:
  privatebin:
    image: privatebin/nginx-fpm-alpine:latest
    pull_policy: always
    restart: always
    read_only: true
    environment:
      - TZ
      - PHP_TZ
    volumes:
      - './privatebin-data:/srv/data'
      - './conf.php:/srv/cfg/conf.php:ro'
    ports:
      - 8080:8080

volumes:
  privatebin-data:
  ```
  
  conf.php is not find, how can I bind mount ?
  Tks
