### DISCUSSION TITLE
How to connect a compose app to a database in the same project?

### DISCUSSION THREAD

**Discussion by dllabs** [Dokploy/dokploy#884] [General]
I have a project `my-project` that contains a Postgres database called `db`, and a compose app.
Dokploy tells me the internal hostname of the database is, say, myproject-db-123456.

When I use that hostname in a container in the compose app, I get an error saying:
`could not translate host name "myproject-db-123456" to address`

The only way I've been able to get containers in the compose app to see the database is add a `networks: dokploy-network` option in docker-compose putting the containers on the `dokploy-network` that Dokploy creates when a domain is added to the compose app.

Given that `dokploy-network` is external-facing, I probably don't want to be doing that, do I? So what settings do I add to my docker-compose so they can see a database that has been set up in the same project? What network are databases on?

This is the docker-compose I use, with the dokploy-network added:

```
services:
       
  webserver:
    build:
      context: ./django
    image: predictions-master
    entrypoint: /entrypoints/webserver_entrypoint.sh
    volumes:
      - predictions_django_static:/usr/src/app/static
      - predictions_bash_history:/commandhistory
    expose:
      - '8000'
    env_file:
      - ./.env
    networks:
      - dokploy-network

  nginx:
    restart: always
    image: nginx:1.27.2-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - predictions_django_static:/var/www/static
    depends_on:
      - webserver
    networks:
      - dokploy-network

volumes:
  predictions_django_static:
  predictions_bash_history:

```
