### DISCUSSION TITLE
Issue running template

### DISCUSSION THREAD

**Discussion by wiggins-philip** [Dokploy/dokploy#908] [Q&A]
I'm trying to use the "yourls" template to, but when I deploy the I receive the following for the mysql container logs
```
Version: '5.7.44'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
2024-12-16T14:21:35.508425Z 2 [Note] Access denied for user '$MYSQL_USER'@'localhost' (using password: YES)
``` 

I believe its the healthchecks that is showing the error. So I updated that to and I've tried other variations

```
healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$yourls", "-p $${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
```
And I get the following error. Any help or guidance would be appreciated.
```
2024-12-16T15:52:18.911261Z 3 [Note] Access denied for user ' yourls'@'localhost' (using password: YES)
```
