### ISSUE TITLE
network conflict

### ISSUE THREAD

**Issue by QThans** [Dokploy/dokploy#1004]
### To Reproduce

using two same docker-compose to create services.

### Current vs. Expected behavior

if deploy 2 compose has same configuration, the second deploy will using the first. for example, if there are all have pg, the second service will connect to the pg from the first service.

### Provide environment information

```bash
Operating System:
    OS: Ubuntu 22.04
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

Yes

**Comment by Siumauricio** [comment]
Hi, yes you are right, this is a bug that I am seeing for some time you can not deploy 2 equal templates because it is possible to mix the information and cause bad gateway errors or something like that and it is because in the dokploy-network the service names must be unique, currently I have not found a way to solve it that is elegant, I know it is something related to networks but I have no idea to solve it, I have tried different methods but none with the success I want without having to do a lot of magic behind compose.

If you have any idea how to solve it in an elegant and direct way that is not something so manual would be great

**Comment by QThans** [comment]
> #821

maybe, You can add a random variable which can into docker-compose?

**Comment by QThans** [comment]
@Siumauricio

**Comment by QThans** [comment]
how about insert service-name into configuration. 
if the original name is pg, we can let it be like: pg-{service-name}. then we can use pg-{service-name} to connect. also can consider insert the random string.
@Siumauricio

**Comment by QThans** [comment]
I think this can solve the problem of official templates at least.

**Comment by Siumauricio** [comment]
Yes, I was thinking about some of that, I just didn't like it because it was something that had to be done manually and I don't know how comfortable people would feel doing that.

I assumed that adding --project-name would add the prefix to all containers, and it does but in the internal way of communication it directly uses the name of the service, so if you have a service like db in multiple compose, there might be problems.

https://docs.docker.com/reference/cli/docker/compose/#options

if a temporary solution is to add a prefix to every container

**Comment by TheOnlyWayUp** [comment]
@Siumauricio is prefixing names a solution to #821 as well?

**Comment by Siumauricio** [comment]
Yes @TheOnlyWayUp , that really should be the only solution, add a prefix to each container, to prevent containers from colliding with names.

**Comment by TheOnlyWayUp** [comment]
@Siumauricio, I believe this solution from @theboringhumane fixes this issue as well - https://github.com/Dokploy/dokploy/issues/821#issuecomment-2582702464.

**Comment by Siumauricio** [comment]
@TheOnlyWayUp Can you add a steps to fix the issue?

**Comment by nktnet1** [comment]
@Siumauricio the way that Coolify handles this is by assigning a `UUID` to each compose resource, and ensuring that they run on a private network named after the resource `UUID` (instead of automatically on the global network, `dokploy-network`).
I previously wrote about these suggestions here:
- https://github.com/Dokploy/dokploy/pull/1129#discussion_r1924436821
- https://github.com/Dokploy/dokploy/discussions/1067#discussioncomment-11896722

This means that common service hostnames like `db` and `redis` will not conflict across services in different compose resources by default (as they are not on the same, global network).

This will be the case for the majority of resources.

---

Additionally, similar to what @QThans mentioned, Coolify implicitly adds the resource `UUID` suffix to the services' container name, volumes, etc - this is visible when you click on "Show Deployable Compose", the equivalent of Dokploy's "Preview Compose" feature.
This is to prepare for the case where services in the resource "opt-in" to be exposed on the global network in order to use (or be used by) external services in other compose resources.
Examples are API services like gotenberg, and `metabase`/`superset` (or any service) that makes use of external databases outside their own compose resource.

When "opt-in", these services are exposed on the global network with a suffixed hostname, i.e. `service-{UUID}`, and will now need to use this new hostname format to talk to each other (or for external services to talk to them).

For example, suppose we "opt in" to expose the [superset compose resource](https://github.com/Dokploy/dokploy/blob/52dbc0d8f1a8a4ab69b86e868308d7a1ddf0d78b/apps/dokploy/templates/superset/docker-compose.yml), which contains the superset, db, and redis services, to the global `dokploy-network`, and the generated resource `UUID` is `abcdefg`.
We will now get unique hostnames like `superset-abcefg`, `db-abcefg`, `redis-abcdefg`, etc on the global `dokploy-network`.

Following Coolify's example, environment variables such as `DOKPLOY_RESOURCE_UUID` and `DOKPLOY_CONTAINER_NAME` can be exposed to each service in case they need to make used of it at runtime
I described a scenario where this was necessary, e.g. for superset, in my PR to Coolify [here](https://github.com/coollabsio/coolify/pull/4945#issue-2809194702).

---

This is not perfect and not saying Dokploy needs to mimic it completely, although personally, I think it is a flexible design that was easy to use and understand. More docs here:
- https://coolify.io/docs/knowledge-base/docker/compose/#connect-to-predefined-networks

**Comment by Siumauricio** [comment]
Thanks @nktnet1 for the explanation and Yes, the truth is that I have thought about that solution, however it seems to me quite a lot of work to be naming for example an environment variable with the prefix of the UUID, which is probably the most optimal solution to prevent any kind of conflict, although I think that coolify internally after deploying the docker compose makes some kind of connection between networks manually.

**Comment by Siumauricio** [comment]
So you mean that before creating the template, in runtime we add a prefix to all services, and expose an environment variable that is `DOKPLOY_SERVICE_UUID` for example, so that users can manipulate the connection to the services? 

I think adding documentation would make it easier, I will try to implement a solution for this, only we would have to change the templates.

Example if we have this wordpress template:

```yaml
version: "3.8"
services:
  wordpress:
    image: wordpress:6.7.1
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress_data:/var/www/html

  db:
    image: mysql:5.7.34
    networks:
      - dokploy-network
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
```

So we might need to convert to like this 
DOKPLOY_SERVICE_UUID = `abcdef`

```yaml
version: "3.8"
services:
  wordpress-${DOKPLOY_SERVICE_UUID}:
    image: wordpress:6.7.1
    environment:
      WORDPRESS_DB_HOST: db-${DOKPLOY_SERVICE_UUID}
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress_data:/var/www/html

  db-${DOKPLOY_SERVICE_UUID}:
    image: mysql:5.7.34
    networks:
      - dokploy-network
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
```

Then in runtime, we will apply the changes so that the template automatically has the assigned values and becomes this



```yaml
version: "3.8"
services:
  wordpress-abcdef:
    image: wordpress:6.7.1
    environment:
      WORDPRESS_DB_HOST: db-abcdef
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress_data:/var/www/html

  db-abcdef:
    image: mysql:5.7.34
    networks:
      - dokploy-network
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
```

Correct me @nktnet1 If I'm wrong, what do you think? this will be apply only to templates
