### ISSUE TITLE
Traefik containers cannot bind settings files

### ISSUE THREAD

**Issue by dungsil** [Dokploy/dokploy#1288]
### To Reproduce

1. Run install script

### Current vs. Expected behavior

Error log:
```
$ docker service ps dokploy --no-trunc

zyx73to875k38y899cdafp8p2   dokploy-traefik.1       traefik:v3.1.2   manager-1   Ready           Rejected 1 second ago     "invalid mount config for type "bind": bind source path does not exist: /etc/dokploy/traefik/traefik.yml"   
szjf5a525sw6lsmvowtwwphj5    \_ dokploy-traefik.1   traefik:v3.1.2   manager-1   Shutdown        Rejected 6 seconds ago    "invalid mount config for type "bind": bind source path does not exist: /etc/dokploy/traefik/traefik.yml"   
bvt5eko3s3nvk2u4ix3go76db    \_ dokploy-traefik.1   traefik:v3.1.2   manager-1   Shutdown        Rejected 11 seconds ago   "invalid mount config for type "bind": bind source path does not exist: /etc/dokploy/traefik/traefik.yml"   
4c8g6hguvrfhzfhh5jpcnuhbn    \_ dokploy-traefik.1   traefik:v3.1.2   manager-1   Shutdown        Rejected 16 seconds ago   "invalid mount config for type "bind": bind source path does not exist: /etc/dokploy/traefik/traefik.yml"   
mr64o10irl8ifpcgklfbervok    \_ dokploy-traefik.1   traefik:v3.1.2   manager-1   Shutdown        Rejected 21 seconds ago   "invalid mount config for type "bind": bind source path does not exist: /etc/dokploy/traefik/traefik.yml"  
```

### Provide environment information

```bash
OS: mac mini m4 / Windows 11 Pro (Intel)
Dokploy: v0.18.2
---
```

### Which area(s) are affected? (Select all that apply)

Traefik

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Additional context

Docker compose file:
```yml
networks:
  dokploy-network:
    external: true

services:
  dokploy:
    image: dokploy/dokploy:latest
    env_file: [ .env ]
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
    networks:
      - dokploy-network
    ports:
      - "15080:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/Users/xxx/Services/dokploy:/etc/dokploy"
```

### Will you send a PR to fix it?

No
