### ISSUE TITLE
Docker-compose: Container can't DNS find the other container

### ISSUE THREAD

**Issue by fishnux** [Dokploy/dokploy#1335]
### To Reproduce

1. Create docker-compose resource:
```yaml
name: emailengine-bundle

services:
    emailengine:
        restart: always
        image: postalsys/emailengine:v2
        #ports:
            # API and web interface
            #- '3000:3000'
            # SMTP for message submission
            #- '2525:2525'
            # IMAP proxy
            #- '9993:9993'
        depends_on:
            - redis
        environment:
            # Configuration to EmailEngine can be passed via environment variables
            # For full list see https://github.com/postalsys/emailengine#config-mapping

            # Settings to write to v1/settings on startup (https://api.emailengine.app/#operation/postV1Settings)
            # The following value is a YAML block scalar string, so make it sure it is properly indented
            # This configuration enables SMTP server for local submission
            EENGINE_SETTINGS: >
                {
                    "smtpServerEnabled": true,
                    "smtpServerPort": 2525,
                    "smtpServerHost": "0.0.0.0",
                    "smtpServerAuthEnabled": true,
                    "smtpServerPassword": "passw0rd"
                }

            # Encryption secret
            EENGINE_SECRET: 'secret'
            # Database connection URL
            EENGINE_REDIS: 'redis://redis:6379/2'
        logging:
            driver: 'json-file'
            options:
                max-size: '200m'
                max-file: '5'

    redis:
        image: redis:7.2
        restart: always
        volumes:
            - redis:/data

volumes:
    redis:
```

### Current vs. Expected behavior

Container shows this in the log:
```
Error: getaddrinfo EAI_AGAIN redis
```

Expected the container to DNS find container redis without problem

### Provide environment information

```bash
Ubuntu 24.04.1 LTS
Dokploy v0.18.4

Hetzner ARM VPS
# uname -a
Linux dokploy 6.8.0-52-generic #53-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 10 23:39:43 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

No

**Comment by vicke4** [comment]
It's not a Dokploy issue. Both services should be on the same network to find each other. Add the same network to both services. If you don't want to create a new network, add the network `dokploy-network`.

**Comment by fishnux** [comment]
> It's not a Dokploy issue. Both services should be on the same network to find each other. Add the same network to both services. If you don't want to create a new network, add the network `dokploy-network`.

Thanks for your suggestion, I'll keep that in mind 😉 

However, I disagree with your statement this isn't a Dokploy issue, because native docker-compose automatically creates a network based on the current project name ([ref](https://docs.docker.com/compose/how-tos/networking/)) - it's not necessary to explicitly define the network in the docker-compose.yml file. As Dokploy features "native" docker-compose support, I consider this a bug

**Comment by vicke4** [comment]
> However, I disagree with your statement this isn't a Dokploy issue, because native docker-compose automatically creates a network based on the current project (folder) name ([ref](https://docs.docker.com/compose/how-tos/networking/)) - it's not necessary to explicitly define the network in the docker-compose.yml file. As Dokploy features (advertises) "native" docker-compose support, I consider this a bug

I'm sure there's a solid reason behind this design decision. Maybe someone more qualified than me will explain.

**Comment by andrekutianski** [comment]
Short answer:

Add the `dokploy-network` network to the services that need to see each other and use the container's "real name" that can be found in the "Docker" menu in Dokploy as the hostname.

Long answer:

Dokploy has its particularities when deploying services, but not so far from docker and docker-compose standards. And when it comes to networks, there is nothing different from a manual deployment of things (Traefik, Docker, Nixpacks, etc), so to speak.

When we are dealing with a local docker-compose project, we often don't worry about network configuration since we use the `container_name` in all services in docker-compose.yml and voila, they all see each other beautifully by their names even if we have never done a single DNS configuration or thought about docker host networks.

But when we bring everything to production, that's when things start to go wrong. Then we discovered Dokploy and believed that it would be the end of all our problems, and it could be. As long as some Linux fundamentals and network topology are taken into account.

If you look a little in the Dokploy documentation about network configuration, you will see different results depending on the type of service you are going to deliver. In the case of a "Composer" type service, you can have several services in the same definition, and this is common and works. For example, you can have 3 services defined in your docker-compose file: `app`, `database`, `redis`. From Dokploy's point of view, you still have only one service, but with 3 different containers running. The Dokploy service is nothing more than a Docker Stack; in fact, the Docker Engine is configured in Swarm mode so that the magic of Dokploy can happen.

These services naturally see each other because they are in the same stack, but they are isolated from the rest of the world, and also from other Dokploy projects and services.

Let's say that now you want to use the Dokploy database service, which requires a specific service and even provides all the parameters for configuration in any other service, but with one detail. Your service (in this case `app` from the previous example) needs to be visible to Dokploy, so that the resolution works and your service sees the database. This is done by defining a pre-existing network called `dokploy-network` in your service, making it part of the same network as the database. It would be like adding a network card to the container with the IP settings of the same network as the database.

The same thing happens when you need to expose your service to Traefik. In addition to the labels in the service that define the Traefik configurations, you also need to include the `dokploy-network` network, so that the container that runs Traefik, and that is in the same network, can find your service and do the proper routing. See an example here https://docs.dokploy.com/docs/core/docker-compose/domains#step-1-add-the-network

Notice that every time the `dokploy-network` network is used, you need to define that it is external:

```yaml
# ... your docker-compose.yml

networks:
dokploy-network:
external: true

```

This is necessary because this network is not managed by the stack (or service), but rather pre-existing, as I have discussed so far. And by doing this, you expose your service to all other services that are on the same network.

According to Dokploy's definition, you should not define `container_name` in your services, and they even warn [here](https://docs.dokploy.com/docs/core/docker-compose/example#updating-your-docker-composeyml) (very discreetly) that strange things can happen if you define this configuration. In fact, this occurs because the one in control of defining the names of the services is Docker Swarm, and if you define `container_name` at some point there may be a name conflict (like an IP conflict, we can say). So to avoid this, Dokploy asks you to remove this parameter from your docker-compose file if it exists.

Ok, but how do I make my service communicate with another container in another service in Dokploy?

First you will need to add the desired services to the `dokploy-network` network exposing it to all of Dokploy and then use the container's "real name", which can be searched and seen in Dokploy's "Docker" menu, in any other service that is also on the same network.

**Comment by sotoplatero** [comment]
You provide a clear explanation of how Dokploy handles networking, but I have a concern. 

If multiple projects run the same application (e.g., multiple Odoo instances) and all services are added to `dokploy-network`, wouldn't there be a risk of conflicts? Identical service names (`web`, `db`) might interfere with each other, causing unintended connections. 

Managing separate networks for each project could be complex, especially in a team environment. Would there be a recommended way to avoid conflicts while keeping networking simple and manageable across multiple projects?

Thanks

**Comment by Siumauricio** [comment]
I deployed your docker compose without modifications and no domains and it works perfectly.

https://github.com/user-attachments/assets/01911a9a-92c9-42c8-ba28-3e2d2214da16

What @vicke4 and @andrekutianski  mentions is correct, dokploy uses literal docker compose build, which is a native docker command so we don't modify its behaviour you can check here what we run in each deploy

https://github.com/Dokploy/dokploy/blob/56af89468aca48d334c7a9571fb9ad453af80ceb/packages/server/src/utils/builders/compose.ts#L62-L80

the way to make your services accessible through a domain is required to join your services to the dokploy-network where the load balancer that is traefik is located, if you don't add the network traefik simply won't know where to look and be able to route your services.


 What you mention @sotoplatero, is a problem that we recently fixed, that basically we isolate all the services of a compose in a private network, and then we join the traefik container to that private network, so that those services are isolated and there are no name conflicts and resources can be shared, by default is enabled since version 0.18.3 you can see the implementation here https://github.com/Dokploy/dokploy/pull/1276, when this toggle is activated it is not necessary to add any network.

![Image](https://github.com/user-attachments/assets/8080f7f6-9b1c-4b07-b482-d47fb93367a5)

**Comment by sotoplatero** [comment]
Great! But what if I have my own repository with compose with template?

**Comment by fishnux** [comment]
Verified working, closing issue

**Comment by andrekutianski** [comment]
> Great! But what if I have my own repository with compose with template?

The isolation feature is only available with raw composer because Dokploy can rewrite this for you. If you using a hosted git you will need to adapt this to use environment variables or any other kind of configuration (file mount resource of Dokploy can also work) to set your service names according to the project.

Dokploy delivers services using Docker Swarm and assigns the project name based on the project ID and service name. This approach ensures that you always have a predictable constant that serves as a prefix for all project services. It is up to you to determine how to implement this.

For example, I'm using the environment variables to set the service names needed and making my application ready from there instead of hard-coded names.

**Comment by njxqlus** [comment]
```yaml
services:
  hello_world:
    image: crccheck/hello-world
    networks:
      - dokploy-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command:
      - tunnel
      - --no-autoupdate
      - run
    networks:
      - dokploy-network
    depends_on:
      - hello_world

networks:
  dokploy-network:
    external: true
```

Am I right with this configuration? So every container should be attached to `dokploy-network` to be _visible_ to other containers in the same docker-compose? Just curious about security, when there are hundred of containers from different projects attached to the same network
