### ISSUE TITLE
I can't connect my database to my app

### ISSUE THREAD

**Issue by sostenesapollo** [Dokploy/dokploy#1336]
### To Reproduce

<img width="1427" alt="Image" src="https://github.com/user-attachments/assets/c968a7e7-17b0-4351-877c-8dac23f1c8eb" />

version: '3.8'

I've created an app with this docker-compose, and ran the app using github and buildpacks, any idea how to make it work ?
```
services:
  pgsql:
    container_name: 'pgsql'
    image: postgres:16-alpine
    ports:
      - '5433:5432'  # Expondo no localhost:5433
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: database_test
      POSTGRES_SHARED_BUFFERS: 2GB

  redis:  
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'  # Expondo no localhost:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - ./redis_data:/data

```

<img width="1383" alt="Image" src="https://github.com/user-attachments/assets/72cac78c-bd8e-4f52-a14e-858c9e8a893f" />

### Current vs. Expected behavior

.

### Provide environment information

```bash
,.
```

### Which area(s) are affected? (Select all that apply)

Docker

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

Yes
