### ISSUE TITLE
Unable to use sticky sessions in traefik

### ISSUE THREAD

**Issue by max-degterev** [Dokploy/dokploy#1487]
### To Reproduce

I have an application running via Dockerfile. I have 4 replicas and application config modified as follows:

```
services:
    development-experiments-z8rb1q-service-30:
      loadBalancer:
        sticky:
          cookie:
            name: sticky
            secure: true
            httpOnly: true
            maxAge: 3600
        servers:
          - url: http://development-experiments-z8rb1q:3000
        passHostHeader: true

```

I also set in global traefik.yml
```
log:
  level: DEBUG
```

Unfortunately although the sticky cookie is set Traefik is unable to route the requests properly and relies on WRR instead:
```
2025-03-13T22:55:08Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:196 > Service selected by WRR: 08ad2223cb1fe15c
2025-03-13T22:55:08Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:196 > Service selected by WRR: 08ad2223cb1fe15c
2025-03-13T22:55:09Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:196 > Service selected by WRR: 08ad2223cb1fe15c
```

It looks like something in the way swarm nodes are launched is preventing sticky sessions from working. For proper 0 downtime support it is crucial to have sticky sessions. Any way to resolve this?

### Current vs. Expected behavior

Traefik balancing load between swarm nodes via sticky cookie and not WRR

### Provide environment information

```bash
not relevant
```

### Which area(s) are affected? (Select all that apply)

Traefik

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

Maybe, need help
