### ISSUE TITLE
Deploy vs Rebuild on docker compose are using different volumes

### ISSUE THREAD

**Issue by WolfspiritM** [Dokploy/dokploy#1492]
### To Reproduce

1. Create a wordpress page from template
2. Set it up
3. Click on "Rebuild"
4. Go to the wordpress page again

### Current vs. Expected behavior

Wordpress data is gone. After clicking on "Deploy" the data is back.
Expected behaviour is: Using the same volume

### Provide environment information

```bash
OS: Ubuntu 24.04
Dokploy: Version v0.20.2
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Additional context

When using "Rebuild" the volumes in the docker compose contain an additional suffix.

On deploy:
```yaml
volumes:
  wordpress_data-website-wordpress-2cteae: null
  db_data-website-wordpress-2cteae: null
```

On rebuild:
```yaml
volumes:
  wordpress_data-website-wordpress-2cteae-website-wordpress-2cteae: null
  db_data-website-wordpress-2cteae-website-wordpress-2cteae: null
```

I also noticed that traffik labels are duplicated when clicking on rebuild.

Every new click on "Rebuild" will add another suffix.

### Will you send a PR to fix it?

No
