### ISSUE TITLE
Add template for Kopia

### ISSUE THREAD

**Issue by maelp** [Dokploy/dokploy#1553]
### What problem will this feature address?

Basic template

```
version: "3"
services:
  kopia:
    image: kopia/kopia:0.19
    container_name: kopia
    hostname: kopia
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    ports:
      - "51515:51515"
    command:
      - server
      - start
      - --tls-generate-cert
      - --disable-csrf-token-checks
      - --address=0.0.0.0:51515
      - --server-username=$KOPIA_USERNAME
      - --server-password=$KOPIA_PASSWORD
    volumes:
        # Mount local folders needed by kopia
        - /mnt/data/kopia:/app
        # Mount local folders to snapshot
        - /mnt/data:/data:ro
        # Mount repositories (to backup somewhere else? like Owncloud?)
        - /mnt/kopia_repository:/repository
        # Mount path for browsing mounted snaphots
        - /tmp/kopia_tmp:/tmp:shared
```

with the Environment defining `TZ, KOPIA_USERNAME, KOPIA_PASSWORD`

### Describe the solution you'd like

Add a template

### Describe alternatives you've considered

Do it manually

### Additional context

Could be interesting to have default backups for Docker volumes and/or a `/mnt/data` disk for dokploy (this is where I store all the data for my containers, I find it "safer" than docker volumes which are a bit less easy to look at and manage)

### Will you send a PR to implement it?

Maybe, need help
