### ISSUE TITLE
Show that Healthtests are failing in the UI

### ISSUE THREAD

**Issue by TeamBattino** [Dokploy/dokploy#1557]
### To Reproduce

1. Create a dokploy.
2. Create a compose deployment like the following:

Compose:
```yml
services:
  keycloak-d8fbf0c3:
    container_name: keycloak-app-d8fbf0c3
    image: quay.io/keycloak/keycloak:latest
    restart: always
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db-d8fbf0c3:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HTTP_ENABLED: 'true'
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: ${KEYCLOAK_HOST}
    depends_on:
      - keycloak-db-d8fbf0c3
    networks:
      - keycloak-net-d8fbf0c3
    command:
      - start
  keycloak-db-d8fbf0c3:
    container_name: keycloak-db-d8fbf0c3
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d keycloak
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - ../files/keycloak-db-d8fbf0c3/data:/var/lib/postgresql/data
    networks:
      - keycloak-net-d8fbf0c3
networks:
  keycloak-net-d8fbf0c3:
    name: keycloak-net-d8fbf0c3
    driver: bridge

```

ENV Variables:
```env
KEYCLOAK_USER=admin
KEYCLOAK_PASSWORD=helloworld
KEYCLOAK_HOST=keycloak.dev.pfadi-meilen-herrliberg.ch
POSTGRES_USER=postgres
POSTGRES_PASSWORD=helloworld
```

Domain mapping: 
  Domain: keycloak.dev.pfadi-meilen-herrliberg.ch
  Port: 8080
  Path / 
  Using Letsencrypt 

### Current vs. Expected behavior

When a docker compose has a Healthcheck that is failing, domains never get assigned. Still the container and runs with no sign of anything has gone wrong.

I would expect the UI to show something is wrong.

### Provide environment information

```bash
Operating System:
  OS: Ubuntu 20.04
  Arch: amd64
Dokploy version: 0.20.8
VPS Provider: Azure Virtual Machine
What applications/services are you tying to deploy?
  Keycloak
```

### Which area(s) are affected? (Select all that apply)

Docker, Traefik, Docker Compose

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

No
