### ISSUE TITLE
Adding a domain to compose type of application doesn't work

### ISSUE THREAD

**Issue by mohit2152sharma** [Dokploy/dokploy#1574]
### To Reproduce

Hi, 
I am using `docker-compose.yml` to create a service. I want to expose this service as an api. I want to expose only one endpoint `api.saral.club/status` to the internet while rest of the endpoints should be internally accessible (accessible by other services like frontend in the same dokploy project). 

What I tried: 
- I have added the `api.saral.club` to my DNS (cloudflare) provider, both `A` and `AAAA` records. 
- Applied the `traefik` labels to the `docker-compose.yml` file (shared below)

When I deploy the service, I was expecting it to create a traefik files in `dynamic` folder (similar to how it created for my frontend application), but I don't see any of these labels showing up. 
- I also tried manually editing the traefik files, adding the rules and services, but that also didn't help.
- Reloading the traefik service also didn't help.
- Lastly, I also tried, by removing the labels and going via the gui route, i.e. I selected the Domains option under my project and added the domain `api.saral.club`, `port` as 8000 (same as backend service). But this also didn't work. For this case, I was expecting that any of the endpoints should be accessible from the internet but none of them were. 
- I always get 404 error.

`docker-compose.yml` file: 

```yml
services:
  backend:
    build:
      context: .
      target: webapp

    environment: *environment

    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "3G"
        reservations:
          cpus: "1"
          memory: "1G"

    # ports:
    #   - "8000:8000"
    expose:
      - 8000
    depends_on:
      celery-worker:
        condition: service_healthy
      celery-beat:
        condition: service_healthy

    # hostname: api.saral.club
    labels:
      - "traefik.http.services.backend-svc.loadbalancer.server.port=8000"

      # Public router - only for /mnemonics/v1/info endpoint
      - "traefik.enable=true"
      - "traefik.http.routers.backend-public.rule=Host(`api.saral.club`) && PathPrefix(`/mnemonics/v1/info`)"
      - "traefik.http.routers.backend-public.entrypoint=websecure"
      - "traefik.http.routers.backend-public.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend-public.priority=100"
      - "traefik.http.routers.backend-public.service=backend-svc"

      # Internal router - for all api.saral.club endpoints
      - "traefik.http.routers.backend-internal.rule=Host(`api.saral.club`)"
      - "traefik.http.routers.backend-internal.entrypoints=websecure"
      - "traefik.http.routers.backend-internal.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend-internal.service=backend-svc"
      - "traefik.http.routers.backend-internal.middlewares=internal-only"
      - "traefik.http.routers.backend-internal.priority=10"

      # Middleware to restrict access to internal network only
      - "traefik.http.middlewares.internal-only.ipwhitelist.sourcerange=172.16.0.0/12,192.168.0.0/16,10.0.0.0/8"
    networks:
      - dokploy-network
      - default

  celery-beat:
    build:
      context: .
      target: celery-beat
    depends_on:
      - redis
    # TODO: move this to docker env?
    environment: *environment

    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "500M"

    healthcheck:
      test: ["CMD-SHELL", "pgrep -af 'celery beat' && exit 0 || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 3
      start_period: 0s

  celery-flower:
    build:
      context: .
      target: celery-flower
    depends_on:
      - redis
    # TODO: move this to docker env?
    environment: *environment
    ports:
      - "5555:5555"

    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "500M"

  celery-worker:
    build:
      context: .
      target: celery
    depends_on:
      - redis
    # TODO: move this to docker env?
    environment: *environment

    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "6G"
        reservations:
          cpus: "2"
          memory: "4G"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery --app src.saral_backend.celery.app:celery_app inspect ping -d celery@$$HOSTNAME",
        ]
      interval: 3s
      timeout: 5s
      retries: 3
      start_period: 0s

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
networks:
  dokploy-network:
    external: true
```

### Current vs. Expected behavior

Current behaviour is described above, expected behavior is the api is accessible after adding traefik labels to the docker-compose file.

### Provide environment information

```bash
Operating system: Ubuntu 24.04
Dokploy version: 0.20.8
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

### Are you deploying the applications where Dokploy is installed or on a remote server?

Remote server

### Will you send a PR to fix it?

Yes
