### ISSUE TITLE
Unnecessary configuration fields

### ISSUE THREAD

**Issue by Hoshino-Yumetsuki** [Dokploy/dokploy#1652]
### To Reproduce

```
Error occurred during watcher callback error="/etc/dokploy/traefik/dynamic/dokploy.yml: field not found, node: passHostHeader" providerName=file
```

### Current vs. Expected behavior

The above error message occurs

### Provide environment information

```bash
Docker
```

### Which area(s) are affected? (Select all that apply)

Traefik

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

No

**Comment by tiredIsa** [comment]
I'm not very experienced, but I had the same problem and this worked for me.

The `passHostHeader: true` should be **under** `loadBalancer`, not inside `servers`.

Working version:
```yaml
services:
  dokploy-service-app:
    loadBalancer:
      passHostHeader: true
      servers:
        - url: http://dokploy:3000
```
