### ISSUE TITLE
support rebuild docker compsoe

### ISSUE THREAD

**Issue by Hoshino-Yumetsuki** [Dokploy/dokploy#1677]
### What problem will this feature address?

Sometimes, docker image only provides the latest tag, which affects the update of docker image. It would be nice to have a rebuild option that ignores cache updates

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Will you send a PR to implement it?

No

**Comment by luoxufeiyan** [comment]
+1.

When using the latest tag in Compose services, Compose fails to pull updated versions of images from the registry after upstream updates. Neither `Deploy` nor `rebuild` triggers an image refresh, even when new versions are available in the registry.

**Comment by sergiolozav2** [comment]
Not sure if I understood the issue correctly, but there's a [pull_policy](https://docs.docker.com/reference/compose-file/services/#pull_policy) option in docker-compose.yml that might be related. I haven’t had a chance to test whether it correctly pulls the latest image after a new deployment, but I’ll try to update this if it does.
Example:
```yml
version: '3.9'

services:
  backend:
    image: registry.gitlab.com/my-repo/my-code:latest
    pull_policy: always
    ports:
      - 4000
    environment:
      NODE_ENV: development 
    restart: always
```
