### ISSUE TITLE
URL Rewrite support

### ISSUE THREAD

**Issue by NekoMio** [Dokploy/dokploy#1700]
### What problem will this feature address?

I am using Dokploy to deploy a [slidev](https://sli.dev/) site, and according to its [documentation](https://sli.dev/guide/hosting#vercel), I need a rewrite when deploying static files. Just like this
```json
{
  "rewrites": [
    { "source": "/(.*)", "destination": "/index.html" }
  ]
}
```

### Describe the solution you'd like

I would like to add a UI similar to the `Redirect` to configure this.

### Describe alternatives you've considered

I now do this by manually configuring the traefik configuration file, but feel like this may be a common feature

### Additional context

Middleware configuration files I used
```yaml
middlewares:
  test-replacepathregex:
    replacePathRegex:
      regex: ^/(.*)/(\d+)
      replacement: /$1/index.html
```

### Will you send a PR to implement it?

Maybe, need help
