### ISSUE TITLE
Support custom headers in Traefik Logs, e.g. Cloudflare's cf-connecting-ip

### ISSUE THREAD

**Issue by nktnet1** [Dokploy/dokploy#1845]
### What problem will this feature address?

When using cloudflare domains with proxy turned on, the client's IP is passed in the header with the key CF-Connecting-IP
- https://developers.cloudflare.com/fundamentals/reference/http-headers/#cf-connecting-ip

We have been receiving many 404s to paths that do not exist in our applications.
Currently, the Traefik request logs only shows the IP of the client, which would be Cloudflare.

### Describe the solution you'd like

It would be helpful if we can also extract custom values from the header to include in the logs.
That way, we can include the `CF-Connecting-IP`.

### Describe alternatives you've considered

Printing out the IP at the application level

### Will you send a PR to implement it?

No

**Comment by Venipa** [comment]
Should this fix your issues?
Adding the trusted proxies should allow these custom headers
(just add these `entryPoints.web(Secure).forwardedHeaders.trustedIps` section
```
entryPoints:
  web:
    address: ':80'
    forwardedHeaders: 
      trustedIPs:
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/12
        - 172.64.0.0/13
        - 131.0.72.0/22
  websecure:
    address: ':443'
    forwardedHeaders: 
      trustedIPs:
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/12
        - 172.64.0.0/13
        - 131.0.72.0/22
    http3:
      advertisedPort: 443
    http:
      tls:
        certResolver: letsencrypt
```

**Comment by alexevladgabriel** [comment]
Hello @nktnet1,

The solution, I've found is to add to static Traefik `access log` the following:
```yaml
  fields:
    headers:
      names:
        X-Forwarded-For: keep
        CF-Connecting-IP: keep
```

This adds the mentioned headers earlier in logs and you can see them inside the dashboard.
