### ISSUE TITLE
Support isolated deployment / randomized compose for compose deployment using a git provider

### ISSUE THREAD

**Issue by yergom** [Dokploy/dokploy#1857]
### What problem will this feature address?

As an example, I have the following compose in a repository:

```
services:
  openobserve:
    image: openobserve/openobserve:v0.14.7-simd
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ZO_ROOT_USER_EMAIL=${ZO_ROOT_USER_EMAIL}
      - ZO_ROOT_USER_PASSWORD=${ZO_ROOT_USER_PASSWORD}
      - ZO_TELEMETRY=false
      - ZO_META_STORE=postgres
      - ZO_META_POSTGRES_DSN=postgres://postgres:postgres@db:5432/openobserve
      - ZO_DATA="/data"
    volumes:
      - openobserve-data:/data
  db:
    image: postgres:17.5
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: openobserve
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  openobserve-data:
  db-data:
```

The resulting compose after adding a domain is

```
services:
  openobserve:
    image: openobserve/openobserve:v0.14.7-simd
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ZO_ROOT_USER_EMAIL=${ZO_ROOT_USER_EMAIL}
      - ZO_ROOT_USER_PASSWORD=${ZO_ROOT_USER_PASSWORD}
      - ZO_TELEMETRY=false
      - ZO_META_STORE=postgres
      - ZO_META_POSTGRES_DSN=postgres://postgres:postgres@db:5432/openobserve
      - ZO_DATA="/data"
    volumes:
      - openobserve-data:/data
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.services-openobserve-ywyve7-jh34f4-5-web.rule=Host(`host)
      - traefik.http.routers.services-openobserve-ywyve7-jh34f4-5-web.entrypoints=web
      - traefik.http.services.services-openobserve-ywyve7-jh34f4-5-web.loadbalancer.server.port=5080
      - traefik.http.routers.services-openobserve-ywyve7-jh34f4-5-web.service=services-openobserve-ywyve7-jh34f4-5-web
      - traefik.http.routers.services-openobserve-ywyve7-jh34f4-5-web.middlewares=redirect-to-https@file
      - traefik.http.routers.services-openobserve-ywyve7-jh34f4-5-websecure.rule=Host(`host`)
      - traefik.http.routers.services-openobserve-ywyve7-jh34f4-5-websecure.entrypoints=websecure
      - traefik.http.services.services-openobserve-ywyve7-jh34f4-5-websecure.loadbalancer.server.port=5080
      - traefik.http.routers.services-openobserve-ywyve7-jh34f4-5-websecure.service=services-openobserve-ywyve7-jh34f4-5-websecure
      - traefik.http.routers.services-openobserve-ywyve7-jh34f4-5-websecure.tls.certresolver=letsencrypt
      - traefik.enable=true
    networks:
      - dokploy-network
  db:
    image: postgres:17.5
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: openobserve
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  openobserve-data: null
  db-data: null
networks:
  dokploy-network:
    external: true
```

Since the db and openobserve are in different networks, they cannot communicate. Also volumes are not randomized/isolated.

### Describe the solution you'd like

I would like to have the possibility of configuring how the compose file is isolated/randomized when using a git provider.

### Describe alternatives you've considered

For now, I cannot depend on the git provider and have to use the raw provider.

### Additional context

Using latest version 0.22.3

### Will you send a PR to implement it?

No
