### ISSUE TITLE
Can't make compose backup for non-default port

### ISSUE THREAD

**Issue by AHTOOOXA** [Dokploy/dokploy#1874]
### To Reproduce

trying to set up Docker Compose backups for my postgres db, the porblem is it running on non default port and i can't see how to set the port in the backups interface

![Image](https://github.com/user-attachments/assets/e99fe891-37df-40d0-83c2-a655d93bf800)

![Image](https://github.com/user-attachments/assets/bbb65519-8e76-4e33-9ad4-a3485c2448b3)

### Current vs. Expected behavior

-

### Provide environment information

```bash
-
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

No

**Comment by Siumauricio** [comment]
Can you please paste your docker compose file

**Comment by AHTOOOXA** [comment]
```
# PRODUCTION COMPOSE FILE

services:
  app:
    container_name: tarot-app
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_WEB_HOST=${VITE_WEB_HOST}
        - VITE_API_HOST=${VITE_API_HOST}
        - VITE_BOT_URL=${VITE_BOT_URL}
        - VITE_POSTHOG_KEY=${VITE_POSTHOG_KEY}
        - VITE_POSTHOG_HOST=${VITE_POSTHOG_HOST}
        - VITE_SENTRY_ORG=${VITE_SENTRY_ORG}
        - VITE_SENTRY_PROJECT=${VITE_SENTRY_PROJECT}
        - VITE_SENTRY_DSN=${VITE_SENTRY_DSN}
        - VITE_SENTRY_AUTH_TOKEN=${VITE_SENTRY_AUTH_TOKEN}
        - VITE_DEBUG=${VITE_DEBUG}
    networks:
      - dokploy-network
    command: yarn start
    restart: always
    env_file:
      - ".env"
    depends_on:
      - webhook
    environment:
      - PORT=4173

  bot:
    container_name: tarot-bot
    build:
      context: ./backend
      dockerfile: ./bot.Dockerfile
    volumes:
      - ./backend/src:/src/
    networks:
      - dokploy-network
    restart: always
    env_file:
      - ".env"
    depends_on:
      - webhook
      - pg_database
      - redis_cache
    command: >
      sh -c "
        /venv/bin/python -m app.tgbot.bot
      "

  webhook:
    container_name: tarot-webhook
    build:
      context: ./backend
      dockerfile: ./web.Dockerfile
    volumes:
      - ./backend/src:/src
    networks:
      - dokploy-network
    restart: always
    env_file:
      - ".env"
    depends_on:
      - pg_database
      - redis_cache
    command: >
      sh -c "
        /venv/bin/alembic upgrade head &&
        /venv/bin/uvicorn app.webhook.app:app --host 0.0.0.0 --port 3779 --workers 2
      "

  worker:
    container_name: tarot-worker
    build:
      context: ./backend
      dockerfile: ./worker.Dockerfile
    networks:
      - dokploy-network
    restart: always
    env_file:
      - ".env"
    depends_on:
      - webhook
      - pg_database
      - redis_cache
    volumes:
      - ./backend/src:/src/
    command: ["/venv/bin/arq", "app.worker.worker.WorkerSettings"]

  pg_database:
    container_name: tarot-postgres
    image: postgres:13-alpine
    networks:
      - dokploy-network
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: "postgres -p 5452"
    env_file:
      - '.env'
    ports:
      - 5452:5452
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  redis_cache:
    container_name: tarot-redis
    image: redis:6.2-alpine
    restart: always
    networks:
      - dokploy-network
    command: redis-server --port 6388 --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    env_file:
      - ".env"
    volumes:
      - cache:/data

volumes:
  pgdata: { }
  cache: { }
  rabbitmq_data: { }

networks:
  dokploy-network:
    external: true

```
