### ISSUE TITLE
Custom redirections in the Compose services

### ISSUE THREAD

**Issue by QuentinMacheda** [Dokploy/dokploy#1963]
### What problem will this feature address?

Unlike application services, **compose services** do not have a _"Redirects"_ setting, allowing the users to redirect from **non-www** to **www** for example. Therefore, I cannot have a redirection from domain.com to www.domain.com. 

### Describe the solution you'd like

**A "Redirects" setting in compose services**, allowing the user to add a redirection, like in the application services.

### Describe alternatives you've considered

I did not find any alternative solutions or workaround so far. 

### Will you send a PR to implement it?

Maybe, need help

**Comment by ThePaulo1** [comment]
When you go to 'Traefik File System' you could add a middleware in middlewares.yml like this:

```
redirect-to-www:
      redirectRegex:
        regex: ^https://domain\.com/?$
        replacement: https://www.domain.com
        permanent: true
```

In your compose file you would then need to add this label to your service:

```
labels:
      - traefik.http.routers.<service_name>.middlewares=redirect-to-www@file
```

The service_name can be found if you click 'Preview Compose' in the top right of the provider section (search for this line
`- traefik.http.routers.<container_name>-<some_number>-websecure.service=<container_name>-<some_number>-websecure`)
