### ISSUE TITLE
Make sure you have installed Redis and it is running. Error: connect ECONNREFUSED 10.0.1.5:6379

### ISSUE THREAD

**Issue by ISerranoDev** [Dokploy/dokploy#1988]
### To Reproduce

Hello, i'm getting this errors:

```
:docker service logs dokploy # Dokploy UI
dokploy.1.s8ku3h0vshqy@ismael    |  WARN  Unsupported engine: wanted: {"node":"^20.16.0"} (current: {"node":"v20.9.0","pnpm":"9.5.0"})
dokploy.1.s8ku3h0vshqy@ismael    | 
dokploy.1.s8ku3h0vshqy@ismael    | > dokploy@v0.22.7 start /app
dokploy.1.s8ku3h0vshqy@ismael    | > node -r dotenv/config dist/server.mjs
dokploy.1.s8ku3h0vshqy@ismael    | 
dokploy.1.s8ku3h0vshqy@ismael    | Make sure you have installed Redis and it is running. Error: connect ECONNREFUSED 10.0.1.5:6379
dokploy.1.s8ku3h0vshqy@ismael    |     at <unknown> (Error: connect ECONNREFUSED 10.0.1.5:6379) {
dokploy.1.s8ku3h0vshqy@ismael    |   errno: -111,
dokploy.1.s8ku3h0vshqy@ismael    |   code: 'ECONNREFUSED',
dokploy.1.s8ku3h0vshqy@ismael    |   syscall: 'connect',
dokploy.1.s8ku3h0vshqy@ismael    |   address: '10.0.1.5',
dokploy.1.s8ku3h0vshqy@ismael    |   port: 6379
dokploy.1.s8ku3h0vshqy@ismael    | }
dokploy.1.s8ku3h0vshqy@ismael    | Default middlewares already exists
dokploy.1.s8ku3h0vshqy@ismael    | Make sure you have installed Redis and it is running. Error: connect ECONNREFUSED 10.0.1.5:6379
dokploy.1.s8ku3h0vshqy@ismael    |     at <unknown> (Error: connect ECONNREFUSED 10.0.1.5:6379) {
dokploy.1.s8ku3h0vshqy@ismael    |   errno: -111,
dokploy.1.s8ku3h0vshqy@ismael    |   code: 'ECONNREFUSED',
dokploy.1.s8ku3h0vshqy@ismael    |   syscall: 'connect',
dokploy.1.s8ku3h0vshqy@ismael    |   address: '10.0.1.5',
dokploy.1.s8ku3h0vshqy@ismael    |   port: 6379
dokploy.1.s8ku3h0vshqy@ismael    | }
```

I only did the command to install:
`curl -sSL https://dokploy.com/install.sh | sh
`

And the network has another address for redis. The same case for postgres. Any ideas or solutions? I'm using a vm inside an OVH server. 

### Current vs. Expected behavior

It dont works, but if i enter another port, returns me a 404 in JSON.

### Provide environment information

```bash
OS: Ubuntu 24.04
```

### Which area(s) are affected? (Select all that apply)

Installation

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Additional context

I tried changing everything and anything works, help :(

### Will you send a PR to fix it?

Maybe, need help

**Comment by Siumauricio** [comment]
Can you check this guide maybe this can help you?

https://docs.dokploy.com/docs/core/troubleshooting#my-dokploy-ui-instance-is-not-accessible

**Comment by ISerranoDev** [comment]
I have encountered my problem. My VPS is a dockered VM, so i cant use swarm to use dokploy.
If someone has this problem, i let you my docker-compose here

```
services:
  redis:
    image: redis:7
    container_name: dokploy-redis
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - dokploy-net

  postgres:
    image: postgres:16
    container_name: dokploy-postgres
    restart: always
    environment:
      POSTGRES_USER: dokploy_user
      POSTGRES_DB: dokploy_db
      POSTGRES_PASSWORD: Your_Secure_Password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dokploy-net
   
  dokploy:
    image: dokploy/dokploy:latest
    container_name: dokploy
    restart: always
    privileged: true
    ports:
      - "3000:3000"
    environment:
      ADVERTISE_ADDR: 172.17.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/dokploy:/etc/dokploy
      - dokploy-docker-config:/root/.docker
    networks:
      - dokploy-net
    depends_on:
      - redis
      - postgres
 
  traefik:
    image: traefik:v3.1.2
    container_name: dokploy-traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "8080:8080"
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    volumes:
      - /etc/dokploy/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /etc/dokploy/traefik/dynamic:/etc/dokploy/traefik/dynamic
      - /etc/dokploy/traefik/certs:/etc/dokploy/traefik/certs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dokploy-net
 
 volumes:
   postgres-data:
   redis-data:
   dokploy-docker-config:

networks:
  dokploy-net:
    driver: bridge
```

One important thing. When you deploy a new app, you must go to your ssh, and add mannually the container to the network called "dokploy_dokploy-network".
And the last step is change in your project service -> Advanced -> Traefik: 
loadBalancer:
        servers:
          - url: http://full-container-name:port

And that's it, you can now access to your url
