### ISSUE TITLE
Allow specifying custom DNS server

### ISSUE THREAD

**Issue by monolithed** [Dokploy/dokploy#2044]
I'm unable to add a new service because my cloud provider has aggressive DNS caching. I managed to flush the DNS cache on the VM by editing /etc/hosts, but that didn’t help. I also added the new IP to the hosts file inside the Traefik and Dokploy containers, but that didn’t solve the issue either.

Do you know where Dokploy stores its DNS cache?
Also, why not allow a setting at the IP level to specify which DNS server to use for lookups?

**Comment by andrekutianski** [comment]
Have you already tried to set DNS directly in service settings? like:

```yml
version: '3.8'
services:
  application:
    image: my-app-image
    dns:
      - 8.8.8.8  # Google Public DNS
      - 8.8.4.4
  database:
    image: my-db-image
```
