### ISSUE TITLE
Can't mount volume on application service

### ISSUE THREAD

**Issue by kerimovok** [Dokploy/dokploy#2052]
### To Reproduce

1. Create an application service.
2. Use Docker with `ghcr.io/muchobien/pocketbase:latest` as Docker image
3. Navigate to the `Advanced` tab
4. Click on `Add Volume`
5. Choose `Bind Volume`
6.  Fill host and mount paths as below
Host path: `../files/pb_data`
Mount path: `/pb_data`
7. Deploy the service
8. Navigate to Swarm
9. See the error

<img width="1147" alt="Image" src="https://github.com/user-attachments/assets/f0638a5d-47dc-47a1-b3af-347bc56b85b9" />

When the host path is filled as `/../files/pb_data` :

<img width="1129" alt="Image" src="https://github.com/user-attachments/assets/73cc42f2-0ece-41fd-ae5c-48ce175f4082" />

Note: When using an application service source used as Docker, the service folder in `/etc/dokploy/applications` **is not** created. That MAY cause the problem, but I am not sure. 

Same paths work in Docker Compose

```yaml
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ../files/pb_data:/pb_data
      - ../files/pb_public:/pb_public
      - ../files/pb_hooks:/pb_hooks
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
```

Please, help me understand how to bind mounts in application services.

### Current vs. Expected behavior

Current: Gets rejected by Swarm with errors.
Expected: To bind mounts.

### Provide environment information

```bash
OS: Debian 12
DokPloy: Version v0.22.7
Hosting: OVH
```

### Which area(s) are affected? (Select all that apply)

Application

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Additional context

I am not using the Pocketbase template, because it is broken too, and it is not as popular as one from `muchobien`

### Will you send a PR to fix it?

No
