### ISSUE TITLE
Environment variables from UI not injected into containers after update from 0.22.7

### ISSUE THREAD

**Issue by Rekwian** [Dokploy/dokploy#2073]
### To Reproduce

1. Create or select a project configured in Docker Compose mode.
e.g :
```
services:
  test:
    image: alpine
    command: sh -c "while true; do sleep 3600; done"
```
2. In the Dokploy UI, define one or more environment variables for the project (e.g., MY_VAR=123).
3. Deploy the project using the UI.
4. Open a terminal in the deployed container using Dokploy or via docker exec.
5. Run the `env` command inside the container.

Observed result:
The environment variable(s) defined via the UI are not present in the container.

### Current vs. Expected behavior

Current behavior: Environment variables defined in the UI are not injected into the containers.

Expected behavior: Variables set in the UI should be present in the container's environment after deployment, as it was in version 0.22.7.

### Provide environment information

```bash
OS: Debian GNU/Linux 12 (bookworm)
Dokploy: 0.23.3
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

No

**Comment by egidiusmengelberg** [comment]
Yeah having the same issue.

**Comment by Siumauricio** [comment]
If you don't reference the environment it will not inject the variable 


```yaml
services:
  test:
    image: alpine
    command: sh -c "while true; do sleep 3600; done"
    environment: 
      - MY_VAR=${MY_VAR}
```

then if you enter to the container you can run PRINTENV

````
/ # printenv
HOSTNAME=3aa043c5cdf4
SHLVL=1
HOME=/root
MY_VAR=123
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
/ # 
```

I have already answered this before
