### ISSUE TITLE
UI Feature for Managing Middleware in Traefik

### ISSUE THREAD

**Issue by binaryYuki** [Dokploy/dokploy#274]
### What problem will this feature address?

I propose an enhancement to the UI to include comprehensive management features for middleware configurations. This functionality will be particularly beneficial for managing and adding middleware, especially in clustered environments where fallback services like error-pages are critical.

#### Key Features

- Middleware Overview Page: A dedicated section in the UI to view all configured middleware.
List all middleware with their current configuration.

- Provide status indicators for active/inactive middleware.
Add/Edit Middleware: Forms to easily add new middleware or edit existing ones.
Support for different middleware types (e.g., error-pages, rate-limit, retry, etc.).
Interactive fields for middleware parameters with validation.

- Middleware Templates: Predefined templates for common middleware configurations.
Quick start templates for frequently used middleware setups.
Custom templates for reusable configurations.

- Cluster-Wide Management: Tools to apply middleware configurations across multiple instances in a cluster. Synchronization options to ensure consistency.
Conflict resolution mechanisms.
Fallback Service Configuration: Enhanced support for configuring fallback services like error-pages.

- UI support for linking services with middleware.
Visualization of fallback service flow.

#### Benefits

- Ease of Use: Simplifies the process of managing middleware, reducing the need for manual configuration edits.
- Efficiency: Speeds up deployment and updates of middleware across clusters.
Error Reduction: Minimizes configuration errors through UI validation and templates.
Visibility: Improves visibility into middleware configurations and their statuses.

#### Use Cases

- Clustered Environments: Quickly deploy and manage middleware across multiple Traefik instances.

- Error Handling: Efficiently set up and manage fallback services for error handling (e.g., custom error pages).

- Performance Management: Easily configure and monitor performance-related middleware such as rate limiting and retries.

**Comment by binaryYuki** [comment]
I'd like to offer an example we use previously.

```yaml
  error-pages:
    image: akkk1234/error-pages:latest
    environment:
      SHOW_DETAILS: "true"
      TEMPLATE_NAME: "connection"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.error-pages-router.rule=HostRegexp(`.+`)"
      - "traefik.http.routers.error-pages-router.priority=10"
      - "traefik.http.routers.error-pages-router.entrypoints=web"
      - "traefik.http.routers.error-pages-router.middlewares=error-pages-middleware"
      - "traefik.http.middlewares.error-pages-middleware.errors.status=400-599"
      - "traefik.http.middlewares.error-pages-middleware.errors.service=error-pages_error-pages"
      - "traefik.http.middlewares.error-pages-middleware.errors.query=/{status}.html"
      - "traefik.http.services.error-pages-service.loadbalancer.server.port=8080"
    networks:
      - traefik-net
```

It is really useful when something went wrong.
