### ISSUE TITLE
Support docker compose applications with private git dependencies

### ISSUE THREAD

**Issue by jonykalavera** [Dokploy/dokploy#290]
### What problem will this feature address?

When your project uses git+ssh dependencies in private repos you need to enable ssh support for docker compose to mount the ssh key. https://docs.docker.com/compose/compose-file/build/#ssh

### Describe the solution you'd like

Given that we already have ssh keys config to clone the repos i'd like those same keys to be used in this case. 

### Describe alternatives you've considered

I managed to get it working by explicitly specifying the SSH key to use in the docker-compose file. 

```yaml
    build:
      context: .
      ssh:
        - default=/etc/dokploy/ssh/wDe6feW2FBEKuQCN_XC26_rsa
```

this feels flaky. the key can be specified with docker-compose build but I don't see such option for docker compose up directly by docker-compose
