### ISSUE TITLE
Git submodules are not cloned

### ISSUE THREAD

**Issue by v3rmine** [Dokploy/dokploy#322]
### To Reproduce

1. Create ~~an application~~ a docker-compose with a git with submodules
2. The Dockerfile to build the app depend on one of the submodule to build
3. Deploy

### Current vs. Expected behavior

Following the previous steps, I expected the project to deploy successfully, but the submodules were not cloned so the build crashed.

### Provide environment information

```bash
Operating System:
  OS: Fedora (kernel 6.9.6-100)
  Arch: amd64
Dokploy version: v0.6.1
VPS Provider: Hetzner
Trying to deploy [Shaarli](https://github.com/shaarli/Shaarli) (a simple php app) with a theme in the submodule
```

### Which area(s) are affected? (Select all that apply)

Application, Docker Compose, Docker

### Additional context

Sorry if it's in the bad issue category, I'm not sure if it's a bug or expected comportment.

**Comment by Siumauricio** [comment]
Hi @v3rmine cna you share the docker file?

**Comment by v3rmine** [comment]
Yes, here it is!

The shape of the git:
```
/modules/
  /shaarli/
    /themes/
      /stack/ => git submodule
    /plugins/
      /umami/
    docker-compose.yml
    Dockerfile
```

The docker-compose:
```yml
services:
  shaarli:
    build:
      context: .
      args:
        VERSION: v0.13.0
    expose:
      - 80
    networks:
      - dokploy-network
    volumes:
      - /var/lib/docker-data/shaarli/data:/var/www/shaarli/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.shaarli.entrypoints=websecure
      - traefik.http.routers.shaarli.rule=Host(`shaarli.docker.localhost`)
      - traefik.http.services.shaarli.loadbalancer.server.port=80

networks:
  dokploy-network:
    external: true
```

The Dockerfile
```Dockerfile
ARG VERSION
FROM ghcr.io/shaarli/shaarli:${VERSION}

COPY ./stack/stack /var/www/shaarli/tpl/stack
COPY ./plugins /var/www/shaarli/plugins
```
