### ISSUE TITLE
Environment variables not being set in container

### ISSUE THREAD

**Issue by andrepcg** [Dokploy/dokploy#385]
### To Reproduce

1. Create app
2. Set environment variables in UI
3. Open terminal in container
4. `printenv`
5. Confirm variables are not set

### Current vs. Expected behavior

Env Variables set in the UI should be set within the container but they're not

### Provide environment information

```bash
Dokploy Version: v0.7.2
VPS provider: AWS
OS: Debian
```

### Which area(s) are affected? (Select all that apply)

Installation

**Comment by Siumauricio** [comment]
Hi @andrepcg, First you need to deploy the application in order to see the enviroments in the terminal, I see one of my projects and the enviroments are visible

**Comment by andrepcg** [comment]
Even after a successful deploy, my ends are still not there. I'm doing a docker composer deploy.

This also raises the question: my container required the env vars to be there before deploying, since it starts an app that needs those vars. I hardcoded those but even after passing a dummy env var in the UI and redeploying, the variables are still not there

**Comment by Siumauricio** [comment]
can you share the docker compose file?

**Comment by Siumauricio** [comment]
I tried to deploy the umami template which have a couple enviroment variables and you can see all the values
![Screenshot 2024-08-27 at 3 59 36 PM](https://github.com/user-attachments/assets/352aa23b-c774-43dc-a6a6-671522b3588c)

**Comment by andrepcg** [comment]
> can you share the docker compose file?

```
services:
  atlantis:
    image: sqill/atlantis-custom
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: server --write-git-creds --repo-config=/atlantis/src/repos.yaml
    expose:
      - 4141
```

Dockerfile

```
FROM ghcr.io/runatlantis/atlantis:latest

ENV TERRAGRUNT_VERSION="v0.66.3"
ENV DEFAULT_TERRAFORM_VERSION=1.9.4

# copy a terraform binary of the version you need
USER root

# Install terragrunt
RUN curl -o /usr/local/bin/terragrunt -fsSL "https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_VERSION}/terragrunt_linux_amd64" \
    && chmod +x /usr/local/bin/terragrunt

COPY repos.yaml /atlantis/src/repos.yaml
```
