### ISSUE TITLE
Grocy is not working

### ISSUE THREAD

**Issue by ashishdotme** [Dokploy/dokploy#388]
### To Reproduce

Used below docker compose file 

```
services:
  grocy:
    image: linuxserver/grocy:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /container/grocy/config:/config
    ports:
      - 9283:80
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grocy.rule=Host(`grocy.ashish.me`)"
      - "traefik.http.routers.grocy.entrypoints=web"
      - "traefik.http.routers.grocy.service=grocy"
      - "traefik.http.services.grocy.loadbalancer.server.port=9283"
networks:
  dokploy-network:
    external: true
```

![image](https://github.com/user-attachments/assets/7cfdc60b-6226-41eb-8391-7774e73c94ea)

Getting bad gateway error when I open the url

![image](https://github.com/user-attachments/assets/f96f96ac-b0ba-4760-8cae-f07da59e58d1)
 

### Current vs. Expected behavior

Grocy is not working

### Provide environment information

```bash
Operating System - Ubuntu
Dokploy - Version: v0.7.1
Application - Grocy
```

### Which area(s) are affected? (Select all that apply)

Traefik

**Comment by Siumauricio** [comment]
This is not a bug, follow this steps 

```yaml
services:
  grocy:
    image: linuxserver/grocy:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /container/grocy/config:/config
    restart: unless-stopped
networks:
  dokploy-network:
    external: true
 ```
Then:

1. Go to domains
2. Add domain
3. Select `grocy` as serviceName
4. In my case I'm using a generated domain so
5. Container port set `80`
6. Deploy


And done your application is deployed
![Screenshot 2024-08-28 at 10 54 45 AM](https://github.com/user-attachments/assets/2e90a4f7-a85c-4aa6-aecf-4bae4e20a609)
