### ISSUE TITLE
[Bug]: Internal host is not accessible.

### ISSUE THREAD

**Issue by kerimovok** [Dokploy/dokploy#391]
### To Reproduce

1. Create a new MongoDB database.
2. Copy username & password & host.
3. Create mongo-express application
```yaml
services:
  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
    restart: always
```
```.env
ME_CONFIG_BASICAUTH_USERNAME=CLIENT_USERNAME
ME_CONFIG_BASICAUTH_PASSWORD=CLIENT_PASSWORD
ME_CONFIG_MONGODB_ADMINUSERNAME=MONGODB_USERNAME
ME_CONFIG_MONGODB_ADMINPASSWORD=MONGODB_PASSWORD
ME_CONFIG_MONGODB_SERVER=INTERNAL_HOST
```
4. Deploy MongoDB
5. Deploy Mongo-Express Client
6. Check `Logs`
```bash
cause: Error: getaddrinfo ENOTFOUND lixaz-mongodb-4d91ab
```

### Current vs. Expected behavior

Current: Internal host is not accessible on other services.
Expected: To be accessible.

### Provide environment information

```bash
OS: Debian
Version: v0.7.2
```

### Which area(s) are affected? (Select all that apply)

Databases

### Additional context

This applies not only to databases but to any service, for example RabbitMQ

**Comment by kerimovok** [comment]
[External Credentials](https://docs.dokploy.com/en/docs/core/databases/connection#external-credentials)

Does it apply to services in the same project too? If so, then we can close the issue. Thanks in advance.

**Comment by Siumauricio** [comment]
Have you tried to add the dokploy-network to mongo-express?

**Comment by kerimovok** [comment]
> Have you tried to add the dokploy-network to mongo-express?

It adds network automatically when you add domain, so yes

```yaml
services:
  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
    restart: always
    labels:
      ...
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
```
