### ISSUE TITLE
Add a mail server template.

### ISSUE THREAD

**Issue by ShubashBiswas** [Dokploy/dokploy#408]
### What problem will this feature address?

I face TLS certificate issues with the docker mail server application

### Describe the solution you'd like

I'm requesting to dokploy developer to create a webmail template using well-known mail application for docker 
Like docker mail server, mailu

### Describe alternatives you've considered

None

**Comment by Eliminationzx** [comment]
bump

**Comment by Eliminationzx** [comment]
I have been working with the docker-mailserver configuration and wanted to contribute by reviewing a potential setup that I believe works as intended. Below is the Docker Compose snippet I’m using: 
```
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    hostname: ${MAILSERVER_HOST}
    ports:
      - "25:25"    # SMTP (STARTTLS)
      - "465:465"  # SMTP (Implicit TLS)
      - "587:587"  # SMTP (STARTTLS)
      - "143:143"  # IMAP (STARTTLS)
      - "993:993"  # IMAP (Implicit TLS)
    volumes:
      - mailserver_mail_data:/var/mail/
      - mailserver_mail_state:/var/mail-state/
      - mailserver_mail_logs:/var/log/mail/
      - mailserver_config:/tmp/docker-mailserver/
      - /etc/dokploy/traefik/dynamic/acme.json:/etc/letsencrypt/acme.json:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_FAIL2BAN=1
      - PERMIT_DOCKER=connected-networks
      - SPOOF_PROTECTION=0
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=${MAILSERVER_HOST}
    cap_add:
      - NET_ADMIN
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "${MAILSERVER_HEALTHCHECK_CMD}"
      timeout: ${MAILSERVER_HEALTHCHECK_TIMEOUT}
      retries: ${MAILSERVER_HEALTHCHECK_RETRIES}
    networks:
      - dokploy-network
      
networks:
  dokploy-network:
    external: true

volumes:
  mailserver_mail_data:
  mailserver_mail_state:
  mailserver_mail_logs:
  mailserver_config:
```

Environment:
```
MAILSERVER_HOST=mail.example.com
MAILSERVER_HEALTHCHECK_CMD=ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1
MAILSERVER_HEALTHCHECK_TIMEOUT=3s
MAILSERVER_HEALTHCHECK_RETRIES=0
```

@Siumauricio 
Looking forward to any suggestions or corrections you may have. I hope this configuration can either be helpful or be improved further to meet the needs of others.

**Comment by SashaGoncharov19** [comment]
![image](https://github.com/user-attachments/assets/54f4fc54-a40c-4ddc-b375-5bdd8cb0328c)
@Eliminationzx the functionality of the deployable should be available out of the box, preferably without additional manipulations

**Comment by DeveloperRaju23** [comment]
Dear @Eliminationzx @SashaGoncharov19 

I am facing an issue with running the docker-mailserver. The deployment was smooth but the main problem occurred during setup emails. 

Steps I followed

1. Create a Service with docker-compose type
2. Copy and paste the code in raw
3. Configured the environments
4. Add a domain: mail.example.com with port 80 and Letsencrypt enabled (tried without adding domain also)
5. Deploy the code
6. Open the terminal to set the email and run the command: setup email add user@example.com Pass123
7. Got the error below

`2024-09-10 02:49:18+00:00 INFO  start-mailserver.sh: Welcome to docker-mailserver v14.0.0
2024-09-10 02:49:18+00:00 INFO  start-mailserver.sh: Checking configuration
2024-09-10 02:49:18+00:00 INFO  start-mailserver.sh: Configuring mail server
2024-09-10 02:49:18+00:00 WARN  start-mailserver.sh: You need at least one mail account to start Dovecot (120s left for account creation before shutdown)
2024-09-10 02:49:28+00:00 WARN  start-mailserver.sh: You need at least one mail account to start Dovecot (110s left for account creation before shutdown)
2024-09-10 02:49:39+00:00 WARN  start-mailserver.sh: _extract_certs_from_acme | Unable to find key and/or cert for 'mail.example.com' in '/etc/letsencrypt/acme.json'
2024-09-10 02:49:39+00:00 WARN  start-mailserver.sh: _extract_certs_from_acme | Unable to find key and/or cert for 'mail.example.com' in '/etc/letsencrypt/acme.json'
2024-09-10 02:49:39+00:00 WARN  start-mailserver.sh: _extract_certs_from_acme | Unable to find key and/or cert for 'example.com' in '/etc/letsencrypt/acme.json'
2024-09-10 02:49:39+00:00 WARN  start-mailserver.sh: letsencrypt (acme.json) failed to identify a certificate to extract
2024-09-10 02:49:39+00:00 ERROR start-mailserver.sh: Cannot find a valid DOMAIN for '/etc/letsencrypt/live/<DOMAIN>/', tried: 'mail.example.com', 'mail.example.com', 'example.com'
2024-09-10 02:49:39+00:00 ERROR start-mailserver.sh: _find_letsencrypt_domain | LETSENCRYPT_DOMAIN appears to be misconfigured, please verify.
2024-09-10 02:49:39+00:00 ERROR start-mailserver.sh: Shutting down
2024-09-10 02:49:40,341 WARN exited: mailserver (exit status 1; not expected)
2024-09-10 02:49:40,341 WARN received SIGTERM indicating exit request`


For more reading:
1.  [Docker Mailserver edge Security | TLS (aka SSL)](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/#traefik)
2. [Tutorials | Mail Server behind a Proxy](https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/mailserver-behind-proxy/)

**Comment by Eliminationzx** [comment]
> ![image](https://private-user-images.githubusercontent.com/65261114/365862125-54f4fc54-a40c-4ddc-b375-5bdd8cb0328c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTAxODAsIm5iZiI6MTcyNTk0OTg4MCwicGF0aCI6Ii82NTI2MTExNC8zNjU4NjIxMjUtNTRmNGZjNTQtYTQwYy00ZGRjLWIzNzUtNWJkZDhjYjAzMjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA2MzEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MzZhZjI4Y2U5ZjE0NDljN2NkZjRmMTViNzFmNDkxM2I2ZjhkN2RiMTcyYWY3NDBiNWYxNTc1OTVmM2VlYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3wkbh8ydiKj9_xZDpuhGpZWipVT03RX-KncdZ71GBMA) @Eliminationzx the functionality of the deployable should be available out of the box, preferably without additional manipulations

Post updated.

**Comment by SashaGoncharov19** [comment]
@Eliminationzx The setup appears to be in order. However, some documentation is required to explain the correct procedure for starting up the mail server.

![image](https://github.com/user-attachments/assets/06c7dc13-d021-4eba-ae41-c9b2325c517e)

**Comment by danielchim** [comment]
> Dear [@Eliminationzx](https://github.com/Eliminationzx) [@SashaGoncharov19](https://github.com/SashaGoncharov19)
> 
> I am facing an issue with running the docker-mailserver. The deployment was smooth but the main problem occurred during setup emails.
> 
> Steps I followed
> 
> 1. Create a Service with docker-compose type
> 2. Copy and paste the code in raw
> 3. Configured the environments
> 4. Add a domain: mail.example.com with port 80 and Letsencrypt enabled (tried without adding domain also)
> 5. Deploy the code
> 6. Open the terminal to set the email and run the command: setup email add [user@example.com](mailto:user@example.com) Pass123
> 7. Got the error below
> 
> 2024-09-10 02:49:18+00:00 INFO start-mailserver.sh: Welcome to docker-mailserver v14.0.0
> 
> 2024-09-10 02:49:18+00:00 INFO start-mailserver.sh: Checking configuration
> 
> 2024-09-10 02:49:18+00:00 INFO start-mailserver.sh: Configuring mail server
> 
> 2024-09-10 02:49:18+00:00 WARN start-mailserver.sh: You need at least one mail account to start Dovecot (120s left for account creation before shutdown)
> 
> 2024-09-10 02:49:28+00:00 WARN start-mailserver.sh: You need at least one mail account to start Dovecot (110s left for account creation before shutdown)
> 
> 2024-09-10 02:49:39+00:00 WARN start-mailserver.sh: _extract_certs_from_acme | Unable to find key and/or cert for 'mail.example.com' in '/etc/letsencrypt/acme.json'
> 
> 2024-09-10 02:49:39+00:00 WARN start-mailserver.sh: _extract_certs_from_acme | Unable to find key and/or cert for 'mail.example.com' in '/etc/letsencrypt/acme.json'
> 
> 2024-09-10 02:49:39+00:00 WARN start-mailserver.sh: _extract_certs_from_acme | Unable to find key and/or cert for 'example.com' in '/etc/letsencrypt/acme.json'
> 
> 2024-09-10 02:49:39+00:00 WARN start-mailserver.sh: letsencrypt (acme.json) failed to identify a certificate to extract
> 
> 2024-09-10 02:49:39+00:00 ERROR start-mailserver.sh: Cannot find a valid DOMAIN for '/etc/letsencrypt/live//', tried: 'mail.example.com', 'mail.example.com', 'example.com'
> 
> 2024-09-10 02:49:39+00:00 ERROR start-mailserver.sh: _find_letsencrypt_domain | LETSENCRYPT_DOMAIN appears to be misconfigured, please verify.
> 
> 2024-09-10 02:49:39+00:00 ERROR start-mailserver.sh: Shutting down
> 
> 2024-09-10 02:49:40,341 WARN exited: mailserver (exit status 1; not expected)
> 
> 2024-09-10 02:49:40,341 WARN received SIGTERM indicating exit request
> 
> After that got another error also
> 
> ![image](https://github.com/user-attachments/assets/ae79deb3-0785-4d5f-9356-2a00acd32827)
> 
> For more reading:
> 
> 1. [Docker Mailserver edge Security | TLS (aka SSL)](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/#traefik)
> 2. [Tutorials | Mail Server behind a Proxy](https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/mailserver-behind-proxy/)

The trick here is you need to make sure the domain you selected has the certificate. Since the server will not expose port 80, you will need to create another service (i.e: phpmyadmin) which exposes port 80 for let's encrypt to make a successful acme challenge, then re-assign the domain back to your mail server, and you're good to go.

**Comment by kerimovok** [comment]
Hi, was someone able to launch Mailu on DokPloy?

**Comment by chrisspeakseh** [comment]
poste.io is wrking fine

**Comment by elieobeid7** [comment]
@chrisspeakseh Please share the template for poste.io

**Comment by angelru** [comment]
So docker-mailserver  isn't available in the Dokploy templates, right?

**Comment by chrisspeakseh** [comment]
> So docker-mailserver  isn't available in the Dokploy templates, right?

Not yet

**Comment by elieobeid7** [comment]
I don't know what's the point of this ticket, at first I believed you, until I tried installing a mail  server using dockploy myself on my own server and then saw that everything you ever wrote on this ticket of is all wrong. all of you.

- You don't need a template to install a mailserver
- You don't need traefik integration to install a service on dokploy
- traefik and caddy and all those gen z reverse proxies are useless, but that's a different topic
- You don't need lets encrypt
- You can't use lets Encrypt, becuase your mail servr won't be able to read the cert anyway, if it's managed by dokploy
- Just use cloudflaire as your SSL ACME provider instead of letsencrypt and get over it, it's all the same, With cloudflaire you don't care about SSL renewals
- Let dokploy serve the mail server docker container on port 80, without SSL, then login to whatever Mail server you want to use and configure it to use cloudflaire SSL
- Poste.io is not working fine, [it's not working at all](https://forums.unraid.net/topic/69507-support-posteio-free-version/page/4/)
- Whenever you want to install any service that has its own webserver or that manages its own SSL, skip letsencrypt, go for cloudflaire SSL, same technique.
- If you want a mail server, here's how to install [stalwart](https://stalw.art/), paste this as raw docker compose, stalwart is the best in the market anyway. Anything else is miles apart; it's not worth installing any other mail server anyway.

```
services:
  stalwart-mail:
    image: stalwartlabs/stalwart:latest
    restart: unless-stopped

    environment:
      TZ: Asia/Dubai # use your timezone

    volumes:
      - ../files/stalwart-mail:/opt/stalwart

    ports:
      - "25:25"        # SMTP
      - "587:587"      # Submission
      - "465:465"      # SMTPS
      - "143:143"      # IMAP
      - "993:993"      # IMAPS
      - "4190:4190"    # Sieve
      - "110:110"      # POP3
      - "995:995"      # POP3S
```

Then setup SSL as I mentioned using cloudflare, you create a new token, and you change the Acme provider in SSL section of stalwart, chatgpt will help with the rest, ask it. My server has 10/10 score.


In conclusion, if you want to install a service X, and that service has its own built in webserver, don't waste your time configuring traeffic, just let dokploy serve on porte 80 and point the webserver of the service X to use cloudflaire.

1. Lets encrypt isn't the only way to have SSL and isn't the best way either.
2. Cloudflare SSL is better than Letsencrypt anyway because it doesn't require renewal, it doesn't require any fidlling around with your webserver, you just generate an api key from cloudflaire and add some DNS entries.

---
Caddy and Traeffic  and whatnot, they're all shitty, here's why:

1. we have nginx, it's production ready, everyone knows it, everyone uses it
2. is caddy traeffix production ready? no. Not as ready as nginx
3. So now dokploy wants to integrate its traeffic, and sends traffic to your containers that use nginx, so 2 reverse proxies already, this is shit already
4. Imagine if you want to protect your site via Cloudflaire proxy, now the request will have to go through 3 proxies, and this in most cases won't work. Good luck surviving any DDOS.
5. In an ideal world, dokploy or any other deployment system shouldn't manage the SSL, your container has its own server, let it handle everything,  on a container per container basis, but kids these days want one solution fits all, one click SSL and here we are.
