### ISSUE TITLE
Cannot reload Traefik, ERR error="service \"dokploy-traefik\" error: port is missing"

### ISSUE THREAD

**Issue by callmewhy** [Dokploy/dokploy#446]
### To Reproduce

1. deploy the latest dokploy
2. click reload Traefik in settings

### Current vs. Expected behavior

Current:
1. reload traefik takes 20+ seconds and fail with message: 'Error to reload the traefik'
2. in traefik logs, there is an error log: `2024-09-13T05:41:14Z ERR error="service \"dokploy-traefik\" error: port is missing" container=dokploy-traefik-qps7gb3qeuy0jhbvmgw4f9p0r providerName=swarm`

Expect to reload successfully without error log

### Provide environment information

```bash
Ubuntu 24
Dokploy Version: v0.8.1
```

### Which area(s) are affected? (Select all that apply)

Traefik

**Comment by Siumauricio** [comment]
Hi @callmewhy , This error is expected, basically it is asking you to assign a domain to the traefik service which does not make much sense, at the time of uploading the version of traefik to v3 I found this error that to access the traefik logs is necessary to be associated with the docker swarm and specify it, otherwise there will be certain times that the logs do not work, for now we can close it does not cause any problems in terms of performance, if anyone has any idea to solve this problem I am open, for now I will close this issue because it is expected.

**Comment by rchaud** [comment]
I found a solution for this. It seems to be traefik with the swarm and docker providers. If you are not using swarm provider (have a cluster) make sure it is set to false and set docker to `watch: true` in your `/etc/dokploy/traefik/traefik.yml`

```
providers:
  swarm:
    exposedByDefault: false
    watch: false
  docker:
    exposedByDefault: false
    watch: true
  file:
    directory: /etc/dokploy/traefik/dynamic
    watch: true
entryPoints:
```

This resolved the issue for me and I am able to see the reload work and I get the green check mark. The error is also gone from the traefik container once it reloads.
