### ISSUE TITLE
Always use dns-01 to apply for certificates

### ISSUE THREAD

**Issue by monlor** [Dokploy/dokploy#447]
### What problem will this feature address?

I use dokploy at home. I don’t have a public IP environment, so I can’t use http-01 to apply for a certificate. I want to configure all domain names to always use dns-01 to apply.

### Describe the solution you'd like

Support the configuration of using http or dns to apply for certificates, support the configuration of cloudflare dns provider

### Describe alternatives you've considered

-

**Comment by robinvalk** [comment]
In #365 support was added for Traefik environment variables. If that feature would work we can use custom environment variables to set the configuration to our liking (DNS verification). I tried it like this:
```
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_DNSCHALLENGE=true
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_DNSCHALLENGE_PROVIDER=cloudflare
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_HTTPCHALLENGE=false
TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_HTTPCHALLENGE_ENTRYPOINT=
CF_DNS_API_TOKEN=*******
```

But this doesn't seem to work as Traefik doesn't support configuring it using both configuration files AND environment files. It's mutually exclusive as described here: https://arc.net/l/quote/tvektmsa

So for modifying the Traefik configuration seems to be impossible.

**Comment by robinvalk** [comment]
Oh I did manage to do it. Following this documentation: https://docs.dokploy.com/en/docs/core/traefik/overview#via-dashboard

You can update the Traefik config files. In the `traefik.yml` file I've changed it to:
```
...
certificatesResolvers:
  letsencrypt:
    acme:
      email: ****
      storage: /etc/dokploy/traefik/dynamic/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
```

And using the feature from #364 I could set the cloudflare DNS edit token:
```
CF_DNS_API_TOKEN=*******
```

This should be a solution to your issue too!
