### ISSUE TITLE
error response from daemon: No such container: select-a-container

### ISSUE THREAD

**Issue by hrohwer** [Dokploy/dokploy#451]
### To Reproduce

I tested on Ubuntu 24.04.1 LTS in a virtualbox VM when I create any service even a template I get the following error message in the logs?'

Error response from daemon: No such container: select-a-container

### Current vs. Expected behavior

Launch service

### Provide environment information

```bash
Ubuntu 24.04.1 LTS
Virtualbox VM
```

### Which area(s) are affected? (Select all that apply)

Installation, Docker

**Comment by Siumauricio** [comment]
You need to deploy first in order to access to the terminal of containers

**Comment by borestad** [comment]
Hi!
I have the same issue. The services is deployed.

It works fine from the tab "logs"
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/39280945-9ea5-40b2-971f-84d6dd6059f8">


..but not from general > open terminal

<img width="960" alt="image" src="https://github.com/user-attachments/assets/bd784278-7eec-42f8-ae60-94956d9f123a">

**Comment by Siumauricio** [comment]
@borestad share your docker compose file

**Comment by Siumauricio** [comment]
Since there is no response I assume the issue is gone, one thing that could be cause is because you are using `container_name` property we explicity say in the docs to remove it https://docs.dokploy.com/en/docs/core/docker-compose/example#updating-your-docker-composeyml

**Comment by borestad** [comment]
Hi @Siumauricio , sorry I missed your reply earlier.
Upgraded to 0.9, but same error unfortunately. BUT ..... I also noticed that I actually hadn't removed the container_name, and it started to work. Great find! 

Maybe this could be some kind of validation error/warning in the UI for future versions? :) 


My compose file:

```
version: "3"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 30001:3000/tcp
      - 81:80/tcp
      - 4431:443/tcp
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    restart: unless-stopped
```
