### ISSUE TITLE
Do not ignore traefik middleware config in compose

### ISSUE THREAD

**Issue by fordnox** [Dokploy/dokploy#484]
### What problem will this feature address?

Ads ability to define custom headers to be sent to docker service

### Describe the solution you'd like

I have this docker compose file

```yml
services:
  ghost:
    image: ghost
    environment:
      url: https://domain.com
      database__client: ${DB_CLIENT:-mysql}
      database__connection__host: ${DB_HOST:-ghost_db}
      database__connection__user: ${DB_USER:-ghost}
      database__connection__password: ${DB_USER_PASS:-DatabasePassword1234}
      database__connection__database: ${DB_NAME:-ghost}      
      mail__transport: SMTP
      mail__options__auth__pass: ${MAIL_OPTIONS_AUTH_PASS}
      mail__options__auth__user: ${MAIL_OPTIONS_AUTH_USER}
      mail__options__secure: ${MAIL_OPTIONS_SECURE:-true}
      mail__options__port: ${MAIL_OPTIONS_PORT:-465}
      mail__options__service: ${MAIL_OPTIONS_SERVICE:-Mailgun}
      mail__options__host: ${MAIL_OPTIONS_HOST}
      mail__from: ${MAIL_FROM}
    networks:
      - dokploy-network
    volumes:
      - ghost_data:/var/lib/ghost/content
    ports:
      - 2368:2368
    labels:
      - traefik.http.routers.ghost.rule=Host(`domain.com`)
      - traefik.http.services.ghost.loadbalancer.server.port=2368
      - traefik.http.middlewares.testHeader.headers.customrequestheaders.x-ghost-proxy=true"
    depends_on:
      - ghost_db

  ghost_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-DatabaseRootPassword54321}
      MYSQL_DATABASE: ${DB_NAME:-ghost}
      MYSQL_USER: ${DB_USER:-ghost}
      MYSQL_PASSWORD: ${DB_USER_PASS:-DatabasePassword1234}
    volumes:
      - ghost_db_data:/var/lib/mysql
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  ghost_db_data:
  ghost_data:
  
 ``` 
 
 Dokploy generate file `/etc/dokploy/compose/cms-ghost-350dbf/code/docker-compose.yml` **ignoring middleware config**
 
 ```yml
 services:
  ghost:
    image: ghost
    environment:
      url: https://ghost.fulba.com
      database__client: ${DB_CLIENT:-mysql}
      database__connection__host: ${DB_HOST:-ghost_db}
      database__connection__user: ${DB_USER:-ghost}
      database__connection__password: ${DB_USER_PASS:-DatabasePassword1234}
      database__connection__database: ${DB_NAME:-ghost}
      mail__transport: SMTP
      mail__options__auth__pass: ${MAIL_OPTIONS_AUTH_PASS}
      mail__options__auth__user: ${MAIL_OPTIONS_AUTH_USER}
      mail__options__secure: ${MAIL_OPTIONS_SECURE:-true}
      mail__options__port: ${MAIL_OPTIONS_PORT:-465}
      mail__options__service: ${MAIL_OPTIONS_SERVICE:-Mailgun}
      mail__options__host: ${MAIL_OPTIONS_HOST}
      mail__from: ${MAIL_FROM}
    networks:
      - dokploy-network
    volumes:
      - ghost_data:/var/lib/ghost/content
    ports:
      - '2368:2368'
    labels:
      - traefik.http.routers.ghost.rule=Host(`ghost.fulba.com`)
      - traefik.http.services.ghost.loadbalancer.server.port=2368
      - traefik.http.middlewares.testHeader.headers.customrequestheaders.x-ghost-proxy=true"
      - traefik.enable=true
      - traefik.http.routers.cms-ghost-350dbf-22-web.rule=Host(`ghost.fulba.com`)
      - traefik.http.routers.cms-ghost-350dbf-22-web.entrypoints=web
      - traefik.http.services.cms-ghost-350dbf-22-web.loadbalancer.server.port=2368
      - traefik.http.routers.cms-ghost-350dbf-22-web.service=cms-ghost-350dbf-22-web
    depends_on:
      - ghost_db
  ghost_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-DatabaseRootPassword54321}
      MYSQL_DATABASE: ${DB_NAME:-ghost}
      MYSQL_USER: ${DB_USER:-ghost}
      MYSQL_PASSWORD: ${DB_USER_PASS:-DatabasePassword1234}
    volumes:
      - ghost_db_data:/var/lib/mysql
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
volumes:
  ghost_db_data: null
  ghost_data: null
  ```

### Describe alternatives you've considered

i was considering adding nginx container to proxy to ghost container, but it a huge hack.

I know that the real problem is in the Ghost cms itself: https://ghost.org/help/run-ghost-from-a-subdirectory/?via=joseph26#reverse-proxy-rules

It should not make redirect when using https as url

### Additional context

It is the first time i need to define middleware for dokploy. Ghost has a strange behaviuor

**Comment by Siumauricio** [comment]
Hey @fordnox,I think that in this case you should add the tags yourself, since you can modify the behavior, the domain section has a preset order and can not be modified, it is possible that the tags due to the order are changing the behavior, could you manually invert the tags and check if it works?

Something like this:

```yaml
 labels:
     - traefik.enable=true
     - traefik.http.routers.cms-ghost-350dbf-22-web.rule=Host(`ghost.fulba.com`)
     - traefik.http.routers.cms-ghost-350dbf-22-web.entrypoints=web
     - traefik.http.services.cms-ghost-350dbf-22-web.loadbalancer.server.port=2368
     - traefik.http.routers.cms-ghost-350dbf-22-web.service=cms-ghost-350dbf-22-web
     - traefik.http.routers.ghost.rule=Host(`ghost.fulba.com`)
     - traefik.http.services.ghost.loadbalancer.server.port=2368
     - traefik.http.middlewares.testHeader.headers.customrequestheaders.x-ghost-proxy=true"
  

```

**Comment by fordnox** [comment]
I was wrong, i just needed to add 

```
     - traefik.http.routers.ghost.middlewares=testHeader
```

to illustrate with more simple example:

```yml
services:
  whoami:
    image: traefik/whoami
    networks:
      - dokploy-network
    command:
      - --port=8084
    ports:
      - 8084:8084
    labels:
      - traefik.enable=true      
      - traefik.http.middlewares.whoamiHeader.headers.customrequestheaders.x-myheader-1=one"
      - traefik.http.middlewares.whoamiHeader.headers.customrequestheaders.x-myheader-2=two"
      - traefik.http.middlewares.whoamiHeader.headers.customrequestheaders.x-myheader-3-three"
      - traefik.http.middlewares.whoamiHeader.headers.customrequestheaders.x-myheader-4=four"      
      - traefik.http.routers.whoami.rule=Host(`who.fulba.com`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.services.whoami.loadbalancer.server.port=8084
      - traefik.http.routers.whoami.middlewares=whoamiHeader
networks:
  dokploy-network:
    external: true
```

Thanks for Dokploy.
