### ISSUE TITLE
Docker compose file

### ISSUE THREAD

**Issue by itschip** [Dokploy/dokploy#6]
Seeing as there are some requirements to running this locally that requires installation of, ex. redis, a docker-compose file would be great to bootstrap the dev env. 

I can take a go at it if you're not already working on it.

**Comment by Rei-x** [comment]
this is an example docker compose that i'm using for dev

```yaml
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: dokploy
      POSTGRES_USER: dokploy
      POSTGRES_PASSWORD: amukds4wi9001583845717ad2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
```
