### ISSUE TITLE
Simple zero-downtime deployment for docker-compose and etc (or at least docs/tutorial)

### ISSUE THREAD

**Issue by AHTOOOXA** [Dokploy/dokploy#617]
### What problem will this feature address?

It would be really handy to have built-in zero-downtime deployment scenario setting

### Describe the solution you'd like

Currently i see only this solution (maybe i am wrong and there is another way, I am a total devops noob) and it's kinda hush to transfer from docker-compose to docker stack make swarm configs and create docker registry and built process separately 

Or at least some docs tutorial that it is possible and quick way to do it 

### Describe alternatives you've considered

I've seen this discussion but it's even less info for docker compose case https://github.com/Dokploy/dokploy/discussions/492

**Comment by Siumauricio** [comment]
I'm sure, but I think docker compose does not support zero downtime, the only one is docker swarm and that's what we just use for applications, unless you use compose stack.

**Comment by AHTOOOXA** [comment]
> I'm sure, but I think docker compose does not support zero downtime, the only one is docker swarm and that's what we just use for applications, unless you use compose stack.

Yeah I get. So what approach would you recommend to achieve zero-downtime?

Like: 1) I push to my git repo 2) builder starts and builds images pushes it to some registry 3) on builder finish docker stack is triggered and does zero-downtime redeploy

I really think some stack+builder built in approach would be awesome to have.

For small projects it's and overkill and too much heavy lifting to manually setup the registry, builder worker and triggers, but no-downtime may be crucial

**Comment by Siumauricio** [comment]
In my case I would recommend you to build the images in a ci/cd and push them to the registry, and then simply trigger the deployment and that's it, I recommend dockerhub is really simple 

https://github.com/Dokploy/dokploy/discussions/492#discussioncomment-10850839

The equivalente for docker stack should be something like this


```yaml
version: '3.8'

services:
  app:
    image: your-app-image:latest
    deploy:
      replicas: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
```
