### ISSUE TITLE
How to use "network_mode: host" in compose

### ISSUE THREAD

**Issue by BaggerFast** [Dokploy/dokploy#663]
### To Reproduce

I want deploy home assistant, this service need "network_mode: host"

```
services:
  ha:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ../files/config:/config
      - ../files/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
    privileged: true
    network_mode: host
```

### Current vs. Expected behavior

But when i deploy, i get this message

```
Initializing deployment
Creating File 'docker-compose.yml' to /etc/dokploy/compose/home-ha-pvjefd/code: ✅

File 'docker-compose.yml' created: ✅

╔══════════════════════════════════════════════════════════════════════════════╗
║                                                                              ║
║ App Name: home-ha-pvjefd                                                     ║
║ Build Compose 🐳                                                             ║
║ Detected: 0 mounts 📂                                                        ║
║ Command: docker compose -p home-ha-pvjefd -f docker-compose.yml up -d        ║
║ --build --remove-orphans                                                     ║
║ Source Type: docker raw ✅                                                   ║
║ Compose Type: docker-compose ✅                                              ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝
service ha declares mutually exclusive `network_mode` and `networks`: invalid compose project
Error ❌
```

### Provide environment information

```bash
Dokploy Version: v0.10.10
Server: Debian 12
Service: home-assistant
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

**Comment by Siumauricio** [comment]
If you are using domains in your compose, is normal this error because when you assign a domain it automatically add the dokploy-network to the service, you can see the converted compose by clicking preview compose

My suggestions will be if you really depends on `network_mode: host` remove the domains, and then add the traefik labels manually you can read more here https://docs.dokploy.com/en/docs/core/docker-compose/domains

**Comment by jannismilz** [comment]
@Siumauricio I have the exact same situation right now. I must use `network_mode` but also need domains.

You said I can just configure them manually. Can I just copy the labels out from the preview compose which is currently generated and looks like:
```yaml
# ...
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.media-helpers-jah7gv-43-web.rule=Host(`mydomain.com`)
      - traefik.http.routers.media-helpers-jah7gv-43-web.entrypoints=web
      - traefik.http.services.media-helpers-jah7gv-43-web.loadbalancer.server.port=1234
      - traefik.http.routers.media-helpers-jah7gv-43-web.service=media-helpers-jah7gv-43-web
      - traefik.http.routers.media-helpers-jah7gv-43-web.middlewares=redirect-to-https@file
      - traefik.http.routers.media-helpers-jah7gv-43-websecure.rule=Host(`mydomain.com`)
      - traefik.http.routers.media-helpers-jah7gv-43-websecure.entrypoints=websecure
      - traefik.http.services.media-helpers-jah7gv-43-websecure.loadbalancer.server.port=1234
      - traefik.http.routers.media-helpers-jah7gv-43-websecure.service=media-helpers-jah7gv-43-websecure
      - traefik.http.routers.media-helpers-jah7gv-43-websecure.tls.certresolver=letsencrypt
      - traefik.enable=true
    networks:
      - dokploy-network
# ...
```

Can I just copy that and remove the `networks` thing and the `traefik.docker.network=dokploy-network` label or what would be the way to go?
