### ISSUE TITLE
Getting 404 or Bad Gateway when trying to access a service via a domain using compose

### ISSUE THREAD

**Issue by okatu-loli** [Dokploy/dokploy#734]
### To Reproduce

1. Create a application
2. deploy vaultwarden with compose
3. deploy and setting a domain
4. access the service via a domain

### Current vs. Expected behavior

I get 404 or Bad Gateway when accessing through the domain name
![image](https://github.com/user-attachments/assets/ab2fac19-d92b-43e0-b8e2-3352f5a5d778)

I can access the correct service through ip+port access
![image](https://github.com/user-attachments/assets/04a15939-0010-4ad3-acb1-65fd4916acd3)

### Provide environment information

```bash
Operating System:
  OS: Debian 12
  Arch: amd64
Dokploy version: v0.12.0'
VPS Provider: Dogyun (https://www.dogyun.com/)
What applications/services are you tying to deploy?：vaultwarden (https://github.com/dani-garcia/vaultwarden)
```

### Which area(s) are affected? (Select all that apply)

Docker Compose, Traefik

**Comment by okatu-loli** [comment]
> Read here https://docs.dokploy.com/docs/core/troubleshooting#docker-compose-domain-not-working

Thanks! I finally solved it.

**Comment by Frits1980** [comment]
Why is your documentation saying using "ports:" is worse then using "expose:", and why is it saying not to use "- 3000:80" and instead using "- 3000 \n -80"
While the official docker manual says otherwise? Also, if I try the things in your docs as "recommended" nothing works anymore.

Though I do get a bad gateway error on phpmyadmin with domain set. But from ip:port it works fine. (that is, when I follow the official docker docs)

```
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - wp_app:/var/www/html
      - ../files/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: wp_db
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-0}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '256M');
        define('DISALLOW_FILE_EDIT', true);
    depends_on:
      wp_db:
        condition: service_healthy
    restart: unless-stopped
 
  wp_db:
    image: mysql:8.4
    restart: unless-stopped
    volumes:
      - wp_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  phpmyadmin:
      image: phpmyadmin
      restart: unless-stopped
      expose:
        - 8001
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=wp_db
        - PMA_USER=root
        - PMA_PASSWORD=$DB_PASSWORD

volumes:
  wp_app:
  wp_data:
````
