### ISSUE TITLE
Gateway Timeout when trying to access a service via a domain using compose

### ISSUE THREAD

**Issue by colorhook** [Dokploy/dokploy#752]
### To Reproduce

1. Create a project using `Compose`
2. Paste raw docker compose configuration

```yaml
x-webapp-env: &webapp-env
  LOGIN_ORIGIN: &trigger-url ${TRIGGER_PROTOCOL:-http}://${TRIGGER_DOMAIN:-localhost:3040}
  APP_ORIGIN: *trigger-url
  DEV_OTEL_EXPORTER_OTLP_ENDPOINT: &trigger-otel ${TRIGGER_PROTOCOL:-http}://${TRIGGER_DOMAIN:-localhost:3040}/otel
  ELECTRIC_ORIGIN: http://electric:3000

x-worker-env: &worker-env
  PLATFORM_HOST: webapp
  PLATFORM_WS_PORT: 3030
  SECURE_CONNECTION: "false"
  OTEL_EXPORTER_OTLP_ENDPOINT: *trigger-otel

volumes:
  postgres-data:
  redis-data:

networks:
  dokploy-network:
    external: true
  web-network:
    external: false

services:
  webapp:
    image: ghcr.io/triggerdotdev/trigger.dev:${TRIGGER_IMAGE_TAG:-v3}
    restart: ${RESTART_POLICY:-unless-stopped}
    env_file:
      - .env
    environment:
      <<: *webapp-env
    ports:
      - 3040:3030
    depends_on:
      - postgres
      - redis
    networks:
      - web-network
      - dokploy-network
    labels:
      - "traefik.enable=true"

  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG:-16}
    restart: ${RESTART_POLICY:-unless-stopped}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - dokploy-network
      - web-network
    ports:
      - 5433:5432
    command:
      - -c
      - wal_level=logical
      
  redis:
    image: redis:${REDIS_IMAGE_TAG:-7}
    restart: ${RESTART_POLICY:-unless-stopped}
    volumes:
      - redis-data:/data
    networks:
      - dokploy-network
      - web-network
    ports:
      - 6389:6379

  docker-provider:
    image: ghcr.io/triggerdotdev/provider/docker:${TRIGGER_IMAGE_TAG:-v3}
    restart: ${RESTART_POLICY:-unless-stopped}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    networks:
      - dokploy-network
      - web-network
    depends_on:
      - webapp
    ports:
      - 9021:9020
    env_file:
      - .env
    environment:
      <<: *worker-env
      PLATFORM_SECRET: $PROVIDER_SECRET

  coordinator:
    image: ghcr.io/triggerdotdev/coordinator:${TRIGGER_IMAGE_TAG:-v3}
    restart: ${RESTART_POLICY:-unless-stopped}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    networks:
      - dokploy-network
      - web-network
    depends_on:
      - webapp
    ports:
      - 9020:9020
    env_file:
      - .env
    environment:
      <<: *worker-env
      PLATFORM_SECRET: $COORDINATOR_SECRET

  electric:
    image: electricsql/electric:${ELECTRIC_IMAGE_TAG:-latest}
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      DATABASE_URL: ${DATABASE_URL}?sslmode=disable
    networks:
      - dokploy-network
      - web-network
    depends_on:
      - postgres
    ports:
      - 3061:3000
```

3. edit environment

```
PORT=3030
REMIX_APP_PORT=3030

NODE_ENV=production
RUNTIME_PLATFORM=docker-compose

V3_ENABLED=true
TRIGGER_TELEMETRY_DISABLED=1
INTERNAL_OTEL_TRACE_DISABLED=1
INTERNAL_OTEL_TRACE_LOGGING_ENABLED=0

POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=postgres
DATABASE_HOST=postgres:5432
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}

# This sets the URL used for direct connections to the database and should only be needed in limited circumstances
# See: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#fields:~:text=the%20shadow%20database.-,directUrl,-No
DIRECT_URL=${DATABASE_URL}

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_TLS_DISABLED=true

# If this is set, emails that are not specified won't be able to log in
# WHITELISTED_EMAILS="authorized@yahoo\.com|authorized@gmail\.com"

# Accounts with these emails will become admins when signing up and get access to the admin panel
# ADMIN_EMAILS="admin@example\.com|another-admin@example\.com"

# If this is set, your users will be able to log in via GitHub
# AUTH_GITHUB_CLIENT_ID=
# AUTH_GITHUB_CLIENT_SECRET=

# E-mail settings
#
# - Ensure the FROM_EMAIL matches what you setup with Resend.com
# - If these are not set, emails will be printed to the console
#
# FROM_EMAIL=
# REPLY_TO_EMAIL=
# RESEND_API_KEY=

# Concurrency limits
#
# - If these are too high, you may run out of resources on your worker. A simple fix is to either re-deploy
#   with lower limits, or set appropriate limits in your trigger.config.ts or directly on your tasks.
#
DEFAULT_ORG_EXECUTION_CONCURRENCY_LIMIT=300
DEFAULT_ENV_EXECUTION_CONCURRENCY_LIMIT=100

# Secrets
#
# - You MUST change these in production!
#
# generate these with `openssl rand -hex 16`
MAGIC_LINK_SECRET=secret # used to encrypt magic link tokens
SESSION_SECRET=secret # used to encrypt session cookies
ENCRYPTION_KEY=ae13021afef0819c3a307ad487071c06 # used to encrypt permanent data
#
# generate these with `openssl rand -hex 32`
PROVIDER_SECRET=provider-secret
COORDINATOR_SECRET=coordinator-secret

# Worker settings
#
HTTP_SERVER_PORT=9020
COORDINATOR_HOST=127.0.0.1
COORDINATOR_PORT=${HTTP_SERVER_PORT}
```

4. Set a custom domain
5. Deploy

### Current vs. Expected behavior

After deployment is completed, the service cannot be accessed via the domain, but accessing it through the IP:Port URL works fine.

After removing the `web-network` from the `webapp` service and keeping only the `dokploy-network`, redeploying resolves the issue, and the domain becomes accessible. This suggests that Traefik might not support multiple networks in this configuration:

```
services:
  webapp:
    image: ghcr.io/triggerdotdev/trigger.dev:${TRIGGER_IMAGE_TAG:-v3}
    restart: ${RESTART_POLICY:-unless-stopped}
    env_file:
      - .env
    environment:
      <<: *webapp-env
    ports:
      - 3040:3030
    depends_on:
      - postgres
      - redis
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
```   
    

### Provide environment information

```bash
OS: Alibaba Cloud Linux 3.2104 U10 (OpenAnolis Edition)
Dokploy: Version: v0.11.2
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

**Comment by LickABrick** [comment]
I believe I have somewhat of the same issue. I have 2 networks as well, but for me it is fixed after I stop and redeploy the app without making any changes at all.

**Comment by Siumauricio** [comment]
This happens by misconfiguration from your side

I strongly suggest to read this https://docs.dokploy.com/docs/core/troubleshooting#docker-compose-domain-not-working

or check this issues: https://github.com/Dokploy/dokploy/issues/656, https://github.com/Dokploy/dokploy/issues/734

**Comment by juandl** [comment]
I think this should be under "Services" -> "Docker Compose." Docs,  i expend hours looking for solution

https://docs.dokploy.com/docs/core/troubleshooting#docker-compose-domain-not-working

**Comment by meepo-it** [comment]
> I believe I have somewhat of the same issue. I have 2 networks as well, but for me it is fixed after I stop and redeploy the app without making any changes at all.
> 
> EDIT: It seems you might have to stop and reploy a few times for it to work.

I’ve encountered this issue many times as well. It always works fine right after the initial startup, but at some point in the future, it suddenly returns a 504 error. After redeploying, it works again. My domain is hosted on Cloudflare.

![Image](https://github.com/user-attachments/assets/eb8c4072-9028-4c6c-9208-3d12cc52e323)

**Comment by JerresonJ** [comment]
I believe you guys are fighting the default behavior of Traefik with multiple networks defined. The reason `stop` and `deploy` works after a handful of tries is because Traefik gets lucky and lands on the network the service is actually on. This is not a reliable fix, as any restarting or re-deploys can cause Traefik to jump to the wrong network again.

You need to toss a label onto the service that defines multiple networks so Traefik knows what network to use.

If you isolated the deployment, specify that isolated network name.

```
    labels:
    - traefik.docker.network=some-project-isolated-network
```

OR if you are not isolated you can use label for the main network which is typically the `dokploy-network`

```
    labels:
    - traefik.docker.network=dokploy-network
```

Dokploy could probably fix this by updating the parser for compose and if finding multiple networks on a service go ahead and add the label accordingly.

**Comment by LickABrick** [comment]
In the end for me [this](https://github.com/Dokploy/dokploy/issues/821#issuecomment-2582702464) fixed the issue permanently. This was also added to the default config, but only if you installed after a certain dokploy version, see [here](https://github.com/Dokploy/dokploy/issues/1190#issuecomment-2614604999)

**Comment by JerresonJ** [comment]
> In the end for me [this](https://github.com/Dokploy/dokploy/issues/821#issuecomment-2582702464) fixed the issue permanently. This was also added to the default config, but only if you installed after a certain dokploy version, see [here](https://github.com/Dokploy/dokploy/issues/1190#issuecomment-2614604999)

If I understand Traefik and Docker Networking correctly.
The fix referenced in that issue will not work for swarm that defines multiple networks w/or without isolation and will not work for standalone that defines multiple networks with isolation.

```
providers:
  swarm:
    exposedByDefault: false
    watch: true
  docker:
    exposedByDefault: false
    watch: true
    network: dokploy-network
```
The above does the following for both Swarm and Standalone

Enables both Swarm and Docker standalone as sources of service discovery.
Prevents auto-exposure of containers unless labeled with `traefik.enable=true`.
Keeps Traefik dynamically updated by watching containers/labels.

However for Standalone containers it is telling Traefik to use the `dokploy-network` by default for service routing.

If you define multiple networks and isolate the deployment for a standard container, the end container will be attached to the isolated unique network, and whatever other custom network you defined. Traefik cannot reliably route without the label designating what network the service lives on. The provider config above does nothing as the standalone container is not on `dokploy-network` at all.

Swarm gets even more troublesome.

If you deploy a swarm service that is not isolated but defines multiple networks, you still need to tell it which one is for Traefik service routing, because the provider config doesn't declare any network at all for swarm. So your end container is attached to `dokploy-network` and `some-other-network` but Traefik has no clue which one to route service to.

Same deal if you deploy a swarm service that is isolated and attached to multiple networks. You still need to tell it which one is for Traefik.


You can probably fix Swarm issue one by defining `network: dokploy-network` for `swarm` provider. So if a non-isolated swarm service is deployed the end container still has `dokploy-network` attached along side whatever other network was defined and the provider config tells Traefik to use `dokploy-network`

Swarm issue two, you just define the network via label and go.
