### ISSUE TITLE
Traefik issue with multi network docker compose

### ISSUE THREAD

**Issue by xenonwellz** [Dokploy/dokploy#778]
### To Reproduce

Create a docker compose file with custom network

### Current vs. Expected behavior

Traefik gets confused and chooses an IP it doesn't have access to. It is meant to use dokploy-network and probably ignore any other configured network

### Provide environment information

```bash
OS: Ubuntu
```

### Which area(s) are affected? (Select all that apply)

Traefik

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Additional context

The workaround i did was to add the traefik label  ```traefik.docker.network=dokploy-network"``` to my docker compose

### Will you send a PR to fix it?

Maybe, need help

**Comment by Siumauricio** [comment]
Can you paste a example of docker compose file which are causing the issue to reproduce it?

**Comment by TheOnlyWayUp** [comment]
@xenonwellz I had this issue with Docker composes on Dokploy, where it would overwrite the default network meaning containers in the same compose couldn't talk to each other. Fixed it by adding
```
image:
  networks:
    - default

networks:
  default:
```
to all my composes. Networking works as expected now, but I had another problem that I will create an issue for.

**Comment by Siumauricio** [comment]
Well since there is no answer I assume the problem is solved.

**Comment by xenonwellz** [comment]
It isn't, I have been really busy... I will send an example later today

**Comment by ggffggg00** [comment]
+1
Same issue on v0.17.8

My Docker compose is simple http hello world server:
``` yaml
version: '3'
services:
  hello-worls:
    image: strm/helloworld-http
    networks:
      - test-net-1
      - test-net-2

networks:
  test-net-1:
    driver: bridge
  test-net-2:
    driver: bridge
```
### Steps to reproduce

1. Create a docker compose application with raw definition
2. Deploy it
3. Add domain to deployed compose (port 80) and redeploy 
At this moment compose with traefik labels looks like this:
``` yaml
version: '3'
services:
  hello-worls:
    image: strm/helloworld-http
    networks:
      - test-net-1
      - test-net-2
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.bug-testbug-fa6v0a-17-web.rule=Host(`same-domain.org`)
      - traefik.http.routers.bug-testbug-fa6v0a-17-web.entrypoints=web
      - traefik.http.services.bug-testbug-fa6v0a-17-web.loadbalancer.server.port=80
      - traefik.http.routers.bug-testbug-fa6v0a-17-web.service=bug-testbug-fa6v0a-17-web
networks:
  test-net-1:
    driver: bridge
  test-net-2:
    driver: bridge
  dokploy-network:
    external: true
```
### Expected behaviour 
Traefik routes ingress traffic inside container to 80 port based on host
### Actual behaviour 
Every request to linked domain dropped with 504 Gateway timeout error. In Traefik Dashboard showed wron IP Subnet

![Image](https://github.com/user-attachments/assets/7e4c77fb-c0f4-4179-85a9-a1eed5a22a1c)

Docker subnets on server `docker network inspect $(docker network ls | awk '$3 == "bridge" { print $1}') | jq -r '.[] | .Name + " " + .IPAM.Config[0].Subnet' -`

![Image](https://github.com/user-attachments/assets/48ce585f-b955-47da-805a-d89ab037fbc7)

Traefik choosen a container IP address on another network that it cannot access. Fragment of `docker inspect` output for container:

![Image](https://github.com/user-attachments/assets/ea223b40-c067-4803-9292-a5105d454aba)

After finding the problem I added a label `traefik.docker.network=dokploy-network"` and now everything works as expected
