### ISSUE TITLE
Services deployed via Dokploy Inaccessible After Customizing Traefik Ports via Environment Variables

### ISSUE THREAD

**Issue by chuyun** [Dokploy/dokploy#804]
### To Reproduce

1. Customize the `TRAEFIK_PORT` and `TRAEFIK_SSL_PORT` environment variables as per the instructions in #130 .
2.  Restart the relevant services.
3. Attempt to access the services through Traefik.

### Current vs. Expected behavior

**Expected Behavior**
The services should be accessible through the customized ports without any issues.

**Actual Behavior**
All reverse-proxied services become inaccessible.

### Provide environment information

```bash
Dokploy Version: v0.13.1
```

### Which area(s) are affected? (Select all that apply)

Traefik

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Additional context

After following the guidance from Issue #130 to customize the environment variables TRAEFIK_PORT and TRAEFIK_SSL_PORT, all services reverse-proxied through Traefik become inaccessible. We need to discuss whether a general solution should be provided in Dokploy to resolve this issue.

### Will you send a PR to fix it?

Maybe, need help

**Comment by ccinoo** [comment]
I also encountered a similar problem, the log is as follows:
`2024-12-09T01:42:50Z ERR error="service \"dokploy-traefik\" error: port is missing" container=dokploy-traefik-wh0bwrkcdizfnoctwu65iqx4b providerName=swarm
Connection closed!
Reason: `

**Comment by aliuq** [comment]
I seem to have encountered the same problem. I could access it before, but since the upgrade, accessing through the domain name only returns `404 page not found`. I am not sure whether it is a problem with my configuration or a problem with dokploy.

**Comment by nktnet1** [comment]
I got it working with the following script, which changes port 80 -> 81 and port 443 -> 444:

```sh
#!/bin/bash
# Ensure the script is run as root
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" >&2
    exit 1
fi

# Port Variables
HTTP_PORT=81
HTTPS_PORT=444
APP_PORT=3000

# Check for Linux OS (not macOS or inside a Docker container)
if [ "$(uname)" = "Darwin" ]; then
    echo "This script must be run on Linux" >&2
    exit 1
fi

if [ -f /.dockerenv ]; then
    echo "This script must be run on a native Linux host" >&2
    exit 1
fi

# Check for occupied ports
if ss -tulnp | grep ":$HTTP_PORT " >/dev/null; then
    echo "Error: Port $HTTP_PORT is already in use" >&2
    exit 1
fi

if ss -tulnp | grep ":$HTTPS_PORT " >/dev/null; then
    echo "Error: Port $HTTPS_PORT is already in use" >&2
    exit 1
fi

if ss -tulnp | grep ":$APP_PORT " >/dev/null; then
    echo "Error: Port $APP_PORT is already in use" >&2
    exit 1
fi

# Function to check if a command exists
command_exists() {
  command -v "$@" > /dev/null 2>&1
}

# Install Docker if it is not installed
if command_exists docker; then
  echo "Docker already installed"
else
  curl -sSL https://get.docker.com | sh
fi

# Initialize Docker Swarm
docker swarm leave --force 2>/dev/null

get_ip() {
    # Try to get IPv4
    local ipv4=$(curl -4s https://ifconfig.io 2>/dev/null)

    if [ -n "$ipv4" ]; then
        echo "$ipv4"
    else
        # Try to get IPv6
        local ipv6=$(curl -6s https://ifconfig.io 2>/dev/null)
        if [ -n "$ipv6" ]; then
            echo "$ipv6"
        fi
    fi
}

advertise_addr="${ADVERTISE_ADDR:-$(get_ip)}"

docker swarm init --advertise-addr $advertise_addr

if [ $? -ne 0 ]; then
    echo "Error: Failed to initialize Docker Swarm" >&2
    exit 1
fi

docker network rm -f dokploy-network 2>/dev/null
docker network create --driver overlay --attachable dokploy-network

echo "Network created"

mkdir -p /etc/dokploy

chmod 777 /etc/dokploy

# Pull and deploy Dokploy
docker pull dokploy/dokploy:latest
docker service create \
  --name dokploy \
  --replicas 1 \
  --network dokploy-network \
  --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
  --mount type=bind,source=/etc/dokploy,target=/etc/dokploy \
  --publish published=$HTTP_PORT,target=80,mode=host \
  --publish published=$HTTPS_PORT,target=443,mode=host \
  --publish published=$APP_PORT,target=3000,mode=host \
  --update-parallelism 1 \
  --update-order stop-first \
  -e PORT=$APP_PORT \
  -e TRAEFIK_SSL_PORT=$HTTPS_PORT \
  -e TRAEFIK_PORT=$HTTP_PORT \
  -e ADVERTISE_ADDR=$advertise_addr \
  dokploy/dokploy:latest

# Output success message
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
BLUE="\033[0;34m"
NC="\033[0m" # No Color
printf "${GREEN}Congratulations, Dokploy is installed!${NC}\n"
printf "${BLUE}Wait 15 seconds for the server to start${NC}\n"
printf "${YELLOW}Please go to http://${advertise_addr}:${APP_PORT}${NC}\n\n"
```

@Siumauricio happy to make a pull request + update the docs if needed ^

**Comment by Siumauricio** [comment]
@nktnet1 would be great if you are able to make a pull request !

**Comment by nktnet1** [comment]
I've made the pull request on the Dokploy/Website repository :)
- https://github.com/Dokploy/website/pull/14

**Comment by Siumauricio** [comment]
@nktnet1 Reviewing carefully the script, why does it assign the https and http port to the dokploy container? when it has nothing to do and the one that should have the exposed port should be the dokploy-traefik container, if you can give details to understand it would be great, I tried the script but it does not work, because if you assign the port 81 and 444 for example it will be assigned to the dokploy container and not to traefik which is who balances the services.

**Comment by nktnet1** [comment]
hmm yeah my bad, I did it in a rush and thought it was working, but turns out not (and doesn't make much sense either). Traefik was basically stopped from starting and through some of my old configurations from coolify, it happened to work.
Will spend some time investigating after the holidays - sorry for the confusion ^.

**Comment by patillacode** [comment]
I am on the same boat. 

Hopefully I'll give you an idea if I specify my scenario!

I installed `dokploy` in a brand new VPS and I just setup a project with one service via the `Compose` option.

Deployment goes fine and accessing the naked IP in the browser works under the `port` I setup in the `docker-compose.yml` file .

Now the issue: when trying to access via a custom domain I get the same _404 behaviour_ described above.

I have tried different ports (`3000`, `5058`, `8000`) without success.

I checked the `traefik` config and it has the ports `80` and `443` as you can see below

```yml
providers:
  swarm:
    exposedByDefault: false
    watch: false
  docker:
    exposedByDefault: false
  file:
    directory: /etc/dokploy/traefik/dynamic
    watch: true
entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: letsencrypt
api:
  insecure: true
certificatesResolvers:
  letsencrypt:
    acme:
      email: email@email.com
      storage: /etc/dokploy/traefik/dynamic/acme.json
      httpChallenge:
        entryPoint: web
```

I am not an expert on this matter at all but I am open to help, 

PS: awesome tool! thanks for making it happen @Siumauricio !

**Comment by patillacode** [comment]
I am out of carrots here...

I have been trying to debug this thing for days and I feel it is something stupid but I just can't see it.

- I can access the dokploy UI via the domain `https://dokploy.mydomain.com`without a problem
- I can access my service via `http://MY_SERVER_IP:5058` without issue
- I cannot access my service via `https://staging.mydomain.com` I keep getting 404.

One weird thing though is the when I click the `Preview compose` button I get my `docker-compose-dokploy.yml` file to the dot except for the `traefik` configuration, it is like tripled, not sure if that might be part of the issue or if it is just how dokploy is showing it to me.

If anyone could share any thoughts on this, it would be greatly appreciated.


Allow me to share my config:

Original `docker-compose-dokploy.yml` in my code base:
```yaml
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ligaconquis'"]
      interval: 30s
      timeout: 3s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - dokploy-network

  website:
    restart: always
    build: .
    command: bash -c "make docker-setup && gunicorn --threads 4 --workers=4 ligaconquis.wsgi -b 0.0.0.0:${DOKPLOY_DOCKER_PORT} --timeout=600"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl --head  --request GET $DJANGO_BASE_URL/status/ | grep '200 OK'"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - media:/ligaconquis/media
    ports:
      - ${DOKPLOY_DOCKER_PORTS}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${DJANGO_BASE_URL}`)"
      - "traefik.http.routers.${CONTAINER_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${CONTAINER_NAME}.tls.certResolver=letsencrypt"
      - "traefik.http.services.${CONTAINER_NAME}.loadbalancer.server.port=${DOKPLOY_DOCKER_PORT}"

volumes:
  postgres_data:
  media:

networks:
  dokploy-network:
    external: true

```

`Preview Compose` button returns this:
```yaml
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    healthcheck:
      test:
        - CMD-SHELL
        - sh -c 'pg_isready -U ligaconquis'
      interval: 30s
      timeout: 3s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - dokploy-network
  website:
    restart: always
    build: .
    command: bash -c "make docker-setup && gunicorn --threads 4 --workers=4 ligaconquis.wsgi -b 0.0.0.0:${DOKPLOY_DOCKER_PORT} --timeout=600"
    env_file:
      - .env
    healthcheck:
      test:
        - CMD-SHELL
        - curl --head  --request GET $DJANGO_BASE_URL/status/ | grep '200 OK'
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - media:/ligaconquis/media
    ports:
      - ${DOKPLOY_DOCKER_PORTS}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${DJANGO_BASE_URL}`)
      - traefik.http.routers.${CONTAINER_NAME}.entrypoints=websecure
      - traefik.http.routers.${CONTAINER_NAME}.tls.certResolver=letsencrypt
      - traefik.http.services.${CONTAINER_NAME}.loadbalancer.server.port=${DOKPLOY_DOCKER_PORT}
      - traefik.http.routers.ligaconquistador-staging-m7ti5h-1-web.rule=Host(`staging.mydomain.com`)
      - traefik.http.routers.ligaconquistador-staging-m7ti5h-1-web.entrypoints=web
      - traefik.http.services.ligaconquistador-staging-m7ti5h-1-web.loadbalancer.server.port=80
      - traefik.http.routers.ligaconquistador-staging-m7ti5h-1-web.service=ligaconquistador-staging-m7ti5h-1-web
      - traefik.http.routers.ligaconquistador-staging-m7ti5h-1-web.middlewares=redirect-to-https@file
      - traefik.http.routers.ligaconquistador-staging-m7ti5h-1-websecure.rule=Host(`staging.mydomain.com`)
      - traefik.http.routers.ligaconquistador-staging-m7ti5h-1-websecure.entrypoints=websecure
      - traefik.http.services.ligaconquistador-staging-m7ti5h-1-websecure.loadbalancer.server.port=80
      - traefik.http.routers.ligaconquistador-staging-m7ti5h-1-websecure.service=ligaconquistador-staging-m7ti5h-1-websecure
      - traefik.http.routers.ligaconquistador-staging-m7ti5h-1-websecure.tls.certresolver=letsencrypt
volumes:
  postgres_data: null
  media: null
networks:
  dokploy-network:
    external: true
```

Note on the above: 
- The `loadbalancer.server.port` is wrong if I am correct, it should say `5058` (my service runs on that port)
- As you can see the `traefik` config is kinda weird, right?


Domain configured in my service (not working - 404 behaviour both `http` & `https`):

![Screenshot 2025-01-01 at 17 49 19](https://github.com/user-attachments/assets/a672fe7c-c355-48b7-95bd-79b6664b3790)

Although I see the request goes to the right IP and for what I understand port:

![Screenshot 2025-01-01 at 17 59 34](https://github.com/user-attachments/assets/c376805a-3242-4ad5-908b-5703c09a6433)


Domain configured for Dokploy (perfectly working):

![Screenshot 2025-01-01 at 17 50 52](https://github.com/user-attachments/assets/3638fed1-5df2-4432-86cb-3020a3fabd48)


Dokploy's `traefik` Config (`/etc/dokploy/traefik/traefik.yml`):

```yaml
providers:
  swarm:
    exposedByDefault: false
    watch: false
  docker:
    exposedByDefault: false
  file:
    directory: /etc/dokploy/traefik/dynamic
    watch: true
entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: letsencrypt
api:
  insecure: true
certificatesResolvers:
  letsencrypt:
    acme:
      email: email@gmail.com
      storage: /etc/dokploy/traefik/dynamic/acme.json
      httpChallenge:
        entryPoint: web
```

My domain's DNS configuration:

![Screenshot 2025-01-01 at 17 54 29](https://github.com/user-attachments/assets/a537468c-109d-4eaa-917a-fee36f85e455)

And the deploy settings (no issues in the logs and the service is running as expected):

![Screenshot 2025-01-01 at 18 03 53](https://github.com/user-attachments/assets/e5b81e34-ddde-4df4-b9c5-332db2186585)

I hope someone can help debug the issue.

Thanks!
