### ISSUE TITLE
when i create a ceritificate how can i use it? its not working and shows in certificates list

### ISSUE THREAD

**Issue by masihgh** [Dokploy/dokploy#90]
### dear dockploy

> thank's a lot for a best open source Paas Platform!

i want to create a certificate for a cpanel host DynamicDNS
an use it for a domain but its not working!

![image](https://github.com/Dokploy/dokploy/assets/48735862/52458125-9b17-4781-81b4-785da84e80bd)
![image](https://github.com/Dokploy/dokploy/assets/48735862/67930d15-f12b-461c-b7e0-26da68a91096)

**Comment by Siumauricio** [comment]
Thank you, glad to hear it's working well!

In the certificate section we do nothing more than create a certificate and place it in a place where traefik can detect it, however just creating it doesn't mean that it works, you need to make some changes in traefik file system tab.

When you create a certificate it will generate a file like this 

```yaml
tls:
  certificates:
    - certFile: "/path/to/cert.crt"
      keyFile: "/path/to/cert.key"
```

then in the traefik.yml you need to change the `TLS` and the configuration should be something like this, this will make by default traefik use the default certificate


```yaml
tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/path/to/cert.crt"
        keyFile: "/path/to/cert.key"
```
