### ISSUE TITLE
Postgres unencrypted

### ISSUE THREAD

**Issue by danverbs** [Dokploy/dokploy#92]
I've set up a postgres instance in one of my projects and set up for external access but when I connect to it using Postico, it says the connection is unencrypted? How do I ensure this is encrypted?

If I set my cloudflare DNS to 'DNS Only' I get this message but can connect, if I set it to 'Proxied' I can't connect at all - the SSL connection is set to 'Full'

**Comment by Siumauricio** [comment]
I will to test this, because I've used pgadmin and dbeaber and 0 issues, probably it may need to adjust the database connection because it depends on the driver the tool are using

**Comment by Siumauricio** [comment]
@danverbs I test and it was working looks like using the domain as `hostname` is not working only with the ip of the vps

**Comment by danverbs** [comment]
Ok so don't use the url provided in Dokploy settings? Just the ip of the vps?

**Comment by Siumauricio** [comment]
Correct @danverbs, for now just use the IP when I have more time I will investigate about this, but for now is functional

**Comment by danverbs** [comment]
I will try this and let you know. Thanks 👍🏻

**Comment by danverbs** [comment]
I tried with just the IP and it still says 'The server doesn't support TLS' and is unencrypted. Could you share the steps you took to set this up?

**Comment by Siumauricio** [comment]
Hey @danverbs , I tested and it was working I share the configuration 

1. Create a postgres database (In my case only set the database name)
2. Expose port, type 5432 and then save.
3. copy the postgresql connection.

![image](https://github.com/Dokploy/dokploy/assets/47042324/df1c9e7a-5c3b-44e6-90fc-09d844593729)

4. go to Postico
![image](https://github.com/Dokploy/dokploy/assets/47042324/7d168e5d-a38f-4302-96e1-c8615e1ba3a7)
5. type the postgresql connection but remember to remove the domain and set the ip of your vps
![image](https://github.com/Dokploy/dokploy/assets/47042324/a134a38b-3102-4d45-91f4-a752e905f907)
6. Click add server
7. Select the database, click on test button it will appear some alert about TLS just accept it
![Screenshot 2024-05-20 at 1 10 00 AM](https://github.com/Dokploy/dokploy/assets/47042324/32ed532c-b764-4edb-a4f7-836aeb7ba3d4)
8. Then click on test to check the connection is working
![image](https://github.com/Dokploy/dokploy/assets/47042324/19f67b1e-d894-4967-bc36-962dccd6aeb5)

**Comment by danverbs** [comment]
Thanks - I can connect as shown in your steps but Postico still says the connection is unencrypted? Surely we want it to be encrypted?

**Comment by Siumauricio** [comment]
The question is that it marks you that it is not a secure connection because we do not implement any configuration for the domain with that port, but making adjustments with some traefik configuration would be enough to achieve that result.

What I recommend in case you are afraid or something like that that the probability that it will happen is really low, is simply when you finish doing your tasks in the database remove the exposed port that way no one will be able to access the database from outside.

**Comment by Apsysikal** [comment]
> Thanks - I can connect as shown in your steps but Postico still says the connection is unencrypted? Surely we want it to be encrypted?

I agree with you, that it should be encrypted or have an option to make it so.
@Siumauricio could you provide a working example config for adding this in traefik? Or is there an option to add it to the creation workflow directly (checkbox or something)?

**Comment by ciocan** [comment]
You could add Traefik labels and put them under a subdomain like db.yourdomain.tld 
In this way, you'll have SSL for the subdomain - you'll connect on the port 80.

**Comment by PaiJi** [comment]
Or we could follow railway's postgres template, where they issue their own certificate internally. 

https://github.com/railwayapp-templates/postgres-ssl

**Comment by shakibhasan09** [comment]
Hi @Siumauricio , I'm trying to connect my PostgreSQL database from cloudflare hyperdrive but it requires SSL/TLS connection. I used (create service -> database -> postgres) option from the ui to create the database. Now I can't find the dockerfile/compose file to modify the config to add traefik config which will allow SSL/TLS. So what should I do now?

Thanks
Sakib

**Comment by Makisuo** [comment]
Yeah would be great if it could somehow define our own SSL certificate or one gets automatically added. Since it is required for a lot of things I do I dont have any databases on dokploy currently sadly.

**Comment by gurgunday** [comment]
For info, Coolify is implementing this and I think it's a must-have

https://github.com/coollabsio/coolify/discussions/3976#discussioncomment-11934111

**Comment by nktnet1** [comment]
Same issue when trying to connect with Power BI - there is no support for unencrypted connections.

<img width="411" alt="Image" src="https://github.com/user-attachments/assets/6d6f332d-1a65-4018-9a95-a4436590f6d2" />

**Comment by nktnet1** [comment]
For anyone looking for instructions to the manual traefik workaround, below are the steps I took.

This is for exposing port 5432 using Traefik on a VPS like Hetzner.

1. SSH into your VPS

1. Create a new dynamic config file, e.g. `postgres.yml`
    ```sh
    sudo vim /etc/dokploy/traefik/dynamic/postgres.yml
    ```
     then paste the content
     ```yaml
     tcp:
       routers:
         postgres-router:
           entryPoints:
             - postgres                                # We will also need to add this to traefik.yml later
           rule: "HostSNI(`postgres.yourdomain.com`)"  # Replace this with your domain/subdomain
           service: postgres-service
           tls:
             certResolver: letsencrypt
     
       services:
         postgres-service:
           loadBalancer:
             servers:
               - address: "project-pg-5hxmoy:5432"     # Replace this with your hostname in the internal db URL
     ```

1. Edit `/etc/dokploy/traefik/traefik.yml` (you can do this in both CLI or Dokploy UI) to have the `postgres` entrypoint:
     ```yaml
    entryPoints:
      web:
        address: ':80'
      websecure:
        address: ':443'
        http:
          tls:
            certResolver: letsencrypt

      # Add the two lines below  <------------
      postgres:
        address: ':5432'

     ```

1. On Dokploy, go to `Web Server` -> `Traefik` -> `Additional Port Mapping` and add the mapping `5432:5432`. Note that **Traefik may be reloaded in this step which will result in downtime** for a few seconds (if not, you will still need to reload `Traefik` manually).

1. In your VPS settings (e.g. Hetzner UI), ensure that you allow port 5432 as inbound in your firewall rules. Also check `ufw` if enabled.

1. Add a DNS entry for your domain/subdomain (e.g. an `A` record pointing to `postgres.yourdomain.com`). If you're using Cloudflare, make sure to turn off proxy (i.e. DNS Only) for this domain/subdomain.

One issue I ran into is, my postgres server version is 17, but oddly, the `psql` client v17 cannot connect (only `psql` 16 and below).

**Comment by SkyfallWasTaken** [comment]
+1 for at least adding an alert - I had no idea that my Postgres databases weren't using SSL and having no SSL is definitely a big security risk that should be communicated

**Comment by dreson4** [comment]
Been looking into this, for now I'm using another workaround, using ssh keys to connect instead of using plain connection which is very risky as everyone can see your password and data in plain text. 

For example
If the database is on server ``1.2.3.4:5432`` and its possible to use an ssh file ``key.ssh`` to connect to the server, You can create an ssh tunnel and pin it to a certain port on your machine which will create a secure connection to the database. 

```
ssh -i key.ssh -f -N -L 5433:localhost:5432 youruser@1.2.3.4
```

This pins port 5432 to your machine port 5433, hence you can just connect postgres to localhost:5433 with ``postgresql://user:password@localhost:5433/postgres?sslmode=disable`` without worrying about security

**Comment by newtondotcom** [comment]
Could be an interesting feature to add in the CLI !

**Comment by sanjaydotpro** [comment]
We need this in dokploy, even [coolify](https://coolify.io/docs/databases/ssl) has it now. 

Most of the clients don't support non-ssl postgres connections now.

**Comment by chartliex** [comment]
> Been looking into this, for now I'm using another workaround, using ssh keys to connect instead of using plain connection which is very risky as everyone can see your password and data in plain text.
> 
> For example If the database is on server `1.2.3.4:5432` and its possible to use an ssh file `key.ssh` to connect to the server, You can create an ssh tunnel and pin it to a certain port on your machine which will create a secure connection to the database.
> 
> ```
> ssh -i key.ssh -f -N -L 5433:localhost:5432 youruser@1.2.3.4
> ```
> 
> This pins port 5432 to your machine port 5433, hence you can just connect postgres to localhost:5433 with `postgresql://user:password@localhost:5433/postgres?sslmode=disable` without worrying about security

But to achieve this, you'd need to expose port 5432, which Postgres uses in Docker, right?
That way, anyone can connect because UFW doesn't block it.

There's no way to create the tunnel without exposing the port, is there?

@dreson4

**Comment by dreson4** [comment]
Nope it works just fine even if docker listens to 127.0.0.1, an ssh tunnel to localhost in that machine makes you appear like you are requesting from localhost. I haven't exposed my docker at all it listens to localhost only.

**Comment by chartliex** [comment]
This is what I'm having trouble understanding: I'm creating the SSH tunnel through both PowerShell and Putty. The connection is established and it's listening on port 5432.
But nothing reaches Postgres, there's no attempt log, and when I try to connect, it times out.

I read some articles and asked for help from IA, but nothing worked.

It only works when I open the port through the DockerPloy panel, but then it exposes it for everyone to connect.

Talking on Discord, they told me that there's no point in creating the SSH tunnel if the host doesn't have a destination because Postgres is "stuck" inside Docker; the port isn't accessible from the host.

I can't make this connection between: Docker Postgres <> VPS <> SSH Tunnel <> My Computer

<img width="1499" height="369" alt="Image" src="https://github.com/user-attachments/assets/bc8add6e-2572-4283-abf1-02117773efa9" />

<img width="1094" height="37" alt="Image" src="https://github.com/user-attachments/assets/bcb1aedb-71a6-461b-a262-44676563d6ac" />

**Comment by kwabe007** [comment]
I followed nktnet's example but still couldn't get it to work. After inspecting the traefik logs i saw the error:

```
client requested unsupported application protocols ([postgresql])
```

Turns out the postgresql connection protocol is not enabled by default so I had to add it manually to `/etc/dokploy/traefik/dynamic/postgres.yml`:
```yml
tcp:
  routers:
    postgres-router:
      entryPoints:
        - postgres                                # We will also need to add this to traefik.yml later
      rule: "HostSNI(`postgres.yourdomain.com`)"  # Replace this with your domain/subdomain
      service: postgres-service
      tls:
        certResolver: letsencrypt

  services:
    postgres-service:
      loadBalancer:
        servers:
          - address: "project-pg-5hxmoy:5432"     # Replace this with your hostname in the internal db URL

# Add this section to enable postgresql protocol
tls:
  options:
    default:
      alpnProtocols:
        - http/1.1
        - h2
        - postgresql
```

After that it worked!
