### ISSUE TITLE
Ports listed in docker-compose are publicly exposed despite the official documentation

### ISSUE THREAD

**Issue by daniel-abramov** [Dokploy/dokploy#934]
### To Reproduce

Use a typical docker-compose yaml for the monitoring stack based on Grafana:

```
version: '3'
services:
  loki:
    image: grafana/loki:2.9.2
    ports:
      - 3100
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - dokploy-network

  # Promtail is very problematic for Docker logs.
  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yaml:/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - dokploy-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`monitoring.mydomain.io`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certResolver=letsencrypt
      - traefik.http.services.grafana.loadbalancer.server.port=3000
```

Note that the ports are mapped not as `3000:3000` or `3100:3100` like I would do in a regular set up, but instead just as `3000` or `3100`.

### Current vs. Expected behavior

This may be a problem with the documentation rather than with implementation as per the [official docs](https://docs.dokploy.com/docs/core/troubleshooting#docker-compose-domain-not-working), the suggested way to map/expose ports is used. However, not mapping the ports explicitly does not prevent exposing the port, standard behavior with docker compose in docker is that mentioning the port without explicitly mapping it within `ports` will just assign a random port on a host machine instead of "not exposing it".

So actually deploying with docker-compose as per official docs, will expose services to the public.

```
myapp-monitoring-jezfth-loki-1                           *******:32796->3100/tcp, [::]:32796->3100/tcp
```

And so on.

Note, that this behavior is different from creating a "Docker Compose" deployment in a "Stack" configuration. If "Stack" is used, then actually even exposing ports explicitly via e.g. `3100:3100` will not expose the ports to the public.

PS: Generally speaking, I think it would be nice if the documentation for the docker compose deployment and the behavior of Dokploy was documented a bit better as currently it requires some trial-and-error to get the things right for docker compose. Maybe I should have created a separate issue for that.

### Provide environment information

```bash
OS: Ubuntu 24.04.1 LTS
Dokploy: v0.15.0
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

Maybe, need help
