### ISSUE TITLE
Docker compose deployment does not properly re-deploy the service after pushed changes

### ISSUE THREAD

**Issue by daniel-abramov** [Dokploy/dokploy#945]
### To Reproduce

Step 1 - Deploy a service with docker compose, e.g. something like:

```
  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yaml:/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - dokploy-network
```

This works fine, the service is deployed, the config is applied.

Step 2 - Update the configuration file and push it to the remote repository.

At this point, no redeployment happens. Even pressing `Deploy` manually does not result in the updated version being deployed.

**A workaround** is to press "Stop" manually and once the service is stopped, press "Deploy" again. Then the service is properly deployed reflecting the changes.

### Current vs. Expected behavior

Current behavior: it behaves as if there were no changes.
Expected behavior: changes are properly updated and the service is re-deployed.

### Provide environment information

```bash
OS: Ubuntu 24.04.1 LTS
Dokploy: v0.15.0
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

Maybe, need help
